In [ ]:
# !pip install --upgrade pip setuptools wheel

Requirement already satisfied: pip in /usr/local/lib/python3.11/dist-packages (25.1.1)
Requirement already satisfied: setuptools in /usr/local/lib/python3.11/dist-packages (80.9.0)
Requirement already satisfied: wheel in /usr/local/lib/python3.11/dist-packages (0.45.1)

In [ ]:
# !pip install --upgrade build

Requirement already satisfied: build in /usr/local/lib/python3.11/dist-packages (1.2.2.post1)
Requirement already satisfied: packaging>=19.1 in /usr/local/lib/python3.11/dist-packages (from build) (24.2)
Requirement already satisfied: pyproject_hooks in /usr/local/lib/python3.11/dist-packages (from build) (1.2.0)

In [ ]:
# !apt-get install -y -qq libboost-all-dev cmake build-essential

In [4]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
#코랩 환경에서는 openCL GPU
# 필수 시스템 패키지 설치
# !apt-get install -y -qq libboost-all-dev cmake build-essential

# # 기존 설치 제거
# !pip uninstall -y lightgbm
# !rm -rf /content/LightGBM

# # ✅ LightGBM 3.2.1 (또는 3.2.0) 클론 - setup.py 기반
# !git clone --branch v3.2.1 --recursive https://github.com/microsoft/LightGBM.git /content/LightGBM

# # GPU 빌드
# %cd /content/LightGBM
# !mkdir build
# %cd build
# !cmake -DUSE_GPU=1 ..
# !make -j4

# # 파이썬 패키지 설치 (setup.py 존재함)
# %cd ../python-package
# !ls  # ← 여기서 setup.py 파일이 보여야 성공 lightgbm  MANIFEST.in  README.rst  setup.py
# !pip install .

WARNING: Skipping lightgbm as it is not installed.
Cloning into '/content/LightGBM'...
remote: Enumerating objects: 35433, done.
remote: Counting objects: 100% (201/201), done.
remote: Compressing objects: 100% (124/124), done.
remote: Total 35433 (delta 134), reused 77 (delta 77), pack-reused 35232 (from 4)
Receiving objects: 100% (35433/35433), 24.02 MiB | 29.04 MiB/s, done.
Resolving deltas: 100% (26333/26333), done.
Note: switching to 'b8e38ec1eb8020052d5b39e31e9f2cb6366fb873'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

Submodule 'include/boost/compute' (https://github.com/boostorg/compute) registered for path 'external_libs/compute'
Submodule 'eigen' (https://gitlab.com/libeigen/eigen.git) registered for path 'external_libs/eigen'
Submodule 'external_libs/fast_double_parser' (https://github.com/lemire/fast_double_parser.git) registered for path 'external_libs/fast_double_parser'
Submodule 'external_libs/fmt' (https://github.com/fmtlib/fmt.git) registered for path 'external_libs/fmt'
Cloning into '/content/LightGBM/external_libs/compute'...
remote: Enumerating objects: 21818, done.
remote: Counting objects: 100% (45/45), done.
remote: Compressing objects: 100% (26/26), done.
remote: Total 21818 (delta 25), reused 21 (delta 19), pack-reused 21773 (from 2)
Receiving objects: 100% (21818/21818), 8.54 MiB | 33.76 MiB/s, done.
Resolving deltas: 100% (17609/17609), done.
Cloning into '/content/LightGBM/external_libs/eigen'...
remote: Enumerating objects: 128425, done.
remote: Counting objects: 100% (46/46), done.
remote: Compressing objects: 100% (31/31), done.
remote: Total 128425 (delta 18), reused 35 (delta 15), pack-reused 128379 (from 1)
Receiving objects: 100% (128425/128425), 106.24 MiB | 47.67 MiB/s, done.
Resolving deltas: 100% (106630/106630), done.
Cloning into '/content/LightGBM/external_libs/fast_double_parser'...
remote: Enumerating objects: 871, done.
remote: Counting objects: 100% (136/136), done.
remote: Compressing objects: 100% (21/21), done.
remote: Total 871 (delta 122), reused 115 (delta 115), pack-reused 735 (from 2)
Receiving objects: 100% (871/871), 858.42 KiB | 11.29 MiB/s, done.
Resolving deltas: 100% (437/437), done.
Cloning into '/content/LightGBM/external_libs/fmt'...
remote: Enumerating objects: 39787, done.
remote: Counting objects: 100% (274/274), done.
remote: Compressing objects: 100% (124/124), done.
remote: Total 39787 (delta 186), reused 151 (delta 149), pack-reused 39513 (from 3)
Receiving objects: 100% (39787/39787), 16.67 MiB | 42.14 MiB/s, done.
Resolving deltas: 100% (26854/26854), done.
Submodule path 'external_libs/compute': checked out '36c89134d4013b2e5e45bc55656a18bd6141995a'
Submodule path 'external_libs/eigen': checked out '8ba1b0f41a7950dc3e1d4ed75859e36c73311235'
Submodule path 'external_libs/fast_double_parser': checked out 'ace60646c02dc54c57f19d644e49a61e7e7758ec'
Submodule 'benchmark/dependencies/abseil-cpp' (https://github.com/abseil/abseil-cpp.git) registered for path 'external_libs/fast_double_parser/benchmarks/dependencies/abseil-cpp'
Submodule 'benchmark/dependencies/double-conversion' (https://github.com/google/double-conversion.git) registered for path 'external_libs/fast_double_parser/benchmarks/dependencies/double-conversion'
Cloning into '/content/LightGBM/external_libs/fast_double_parser/benchmarks/dependencies/abseil-cpp'...
remote: Enumerating objects: 31886, done.
remote: Counting objects: 100% (3/3), done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 31886 (delta 0), reused 0 (delta 0), pack-reused 31883 (from 3)
Receiving objects: 100% (31886/31886), 18.04 MiB | 37.17 MiB/s, done.
Resolving deltas: 100% (24984/24984), done.
Cloning into '/content/LightGBM/external_libs/fast_double_parser/benchmarks/dependencies/double-conversion'...
remote: Enumerating objects: 1573, done.
remote: Counting objects: 100% (448/448), done.
remote: Compressing objects: 100% (116/116), done.
remote: Total 1573 (delta 387), reused 334 (delta 332), pack-reused 1125 (from 3)
Receiving objects: 100% (1573/1573), 7.12 MiB | 28.60 MiB/s, done.
Resolving deltas: 100% (1027/1027), done.
Submodule path 'external_libs/fast_double_parser/benchmarks/dependencies/abseil-cpp': checked out 'd936052d32a5b7ca08b0199a6724724aea432309'
Submodule path 'external_libs/fast_double_parser/benchmarks/dependencies/double-conversion': checked out 'f4cb2384efa55dee0e6652f8674b05763441ab09'
Submodule path 'external_libs/fmt': checked out 'cc09f1a6798c085c325569ef466bcdcffdc266d4'
/content/LightGBM
/content/LightGBM/build
CMake Deprecation Warning at CMakeLists.txt:26 (cmake_minimum_required):
  Compatibility with CMake < 3.10 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value.  Or, use the <min>...<max> syntax
  to tell CMake that the project requires at least <min> but has been updated
  to work with policies introduced by <max> or earlier.


-- The C compiler identification is GNU 11.4.0
-- The CXX compiler identification is GNU 11.4.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found OpenMP_C: -fopenmp (found version "4.5")
-- Found OpenMP_CXX: -fopenmp (found version "4.5")
-- Found OpenMP: TRUE (found version "4.5")
-- Looking for CL_VERSION_3_0
-- Looking for CL_VERSION_3_0 - found
-- Found OpenCL: /usr/lib/x86_64-linux-gnu/libOpenCL.so (found version "3.0")
-- OpenCL include directory: /usr/include
CMake Warning (dev) at CMakeLists.txt:148 (find_package):
  Policy CMP0167 is not set: The FindBoost module is removed.  Run "cmake
  --help-policy CMP0167" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found Boost: /usr/lib/x86_64-linux-gnu/cmake/Boost-1.74.0/BoostConfig.cmake (found suitable version "1.74.0", minimum required is "1.56.0") found components: filesystem system
-- Performing Test MM_PREFETCH
-- Performing Test MM_PREFETCH - Success
-- Using _mm_prefetch
-- Performing Test MM_MALLOC
-- Performing Test MM_MALLOC - Success
-- Using _mm_malloc
-- Configuring done (0.8s)
-- Generating done (0.0s)
-- Build files have been written to: /content/LightGBM/build
[  1%] Building CXX object CMakeFiles/lightgbm.dir/src/main.cpp.o
[  4%] Building CXX object CMakeFiles/_lightgbm.dir/src/boosting/gbdt.cpp.o
[  4%] Building CXX object CMakeFiles/_lightgbm.dir/src/boosting/gbdt_model_text.cpp.o
[  5%] Building CXX object CMakeFiles/_lightgbm.dir/src/boosting/boosting.cpp.o
[  7%] Building CXX object CMakeFiles/lightgbm.dir/src/application/application.cpp.o
[  8%] Building CXX object CMakeFiles/_lightgbm.dir/src/boosting/gbdt_prediction.cpp.o
[ 10%] Building CXX object CMakeFiles/_lightgbm.dir/src/boosting/prediction_early_stop.cpp.o
[ 11%] Building CXX object CMakeFiles/_lightgbm.dir/src/io/bin.cpp.o
[ 13%] Building CXX object CMakeFiles/_lightgbm.dir/src/io/config.cpp.o
[ 14%] Building CXX object CMakeFiles/lightgbm.dir/src/boosting/boosting.cpp.o
[ 15%] Building CXX object CMakeFiles/_lightgbm.dir/src/io/config_auto.cpp.o
[ 17%] Building CXX object CMakeFiles/_lightgbm.dir/src/io/dataset.cpp.o
[ 18%] Building CXX object CMakeFiles/_lightgbm.dir/src/io/dataset_loader.cpp.o
[ 20%] Building CXX object CMakeFiles/lightgbm.dir/src/boosting/gbdt.cpp.o
[ 21%] Building CXX object CMakeFiles/_lightgbm.dir/src/io/file_io.cpp.o
[ 23%] Building CXX object CMakeFiles/_lightgbm.dir/src/io/json11.cpp.o
[ 24%] Building CXX object CMakeFiles/lightgbm.dir/src/boosting/gbdt_model_text.cpp.o
[ 26%] Building CXX object CMakeFiles/_lightgbm.dir/src/io/metadata.cpp.o
[ 27%] Building CXX object CMakeFiles/_lightgbm.dir/src/io/parser.cpp.o
[ 28%] Building CXX object CMakeFiles/_lightgbm.dir/src/io/train_share_states.cpp.o
[ 30%] Building CXX object CMakeFiles/_lightgbm.dir/src/io/tree.cpp.o
[ 31%] Building CXX object CMakeFiles/lightgbm.dir/src/boosting/gbdt_prediction.cpp.o
[ 33%] Building CXX object CMakeFiles/_lightgbm.dir/src/metric/dcg_calculator.cpp.o
[ 34%] Building CXX object CMakeFiles/lightgbm.dir/src/boosting/prediction_early_stop.cpp.o
[ 36%] Building CXX object CMakeFiles/_lightgbm.dir/src/metric/metric.cpp.o
[ 37%] Building CXX object CMakeFiles/lightgbm.dir/src/io/bin.cpp.o
[ 39%] Building CXX object CMakeFiles/_lightgbm.dir/src/network/ifaddrs_patch.cpp.o
[ 40%] Building CXX object CMakeFiles/_lightgbm.dir/src/network/linker_topo.cpp.o
[ 42%] Building CXX object CMakeFiles/_lightgbm.dir/src/network/linkers_mpi.cpp.o
[ 43%] Building CXX object CMakeFiles/_lightgbm.dir/src/network/linkers_socket.cpp.o
[ 44%] Building CXX object CMakeFiles/_lightgbm.dir/src/network/network.cpp.o
[ 46%] Building CXX object CMakeFiles/_lightgbm.dir/src/objective/objective_function.cpp.o
[ 47%] Building CXX object CMakeFiles/_lightgbm.dir/src/treelearner/cuda_tree_learner.cpp.o
[ 49%] Building CXX object CMakeFiles/_lightgbm.dir/src/treelearner/data_parallel_tree_learner.cpp.o
[ 50%] Building CXX object CMakeFiles/_lightgbm.dir/src/treelearner/feature_parallel_tree_learner.cpp.o
In file included from /usr/include/CL/cl.h:20,
                 from /content/LightGBM/external_libs/compute/include/boost/compute/cl.hpp:19,
                 from /content/LightGBM/external_libs/compute/include/boost/compute/config.hpp:16,
                 from /content/LightGBM/external_libs/compute/include/boost/compute/buffer.hpp:14,
                 from /content/LightGBM/external_libs/compute/include/boost/compute/core.hpp:18,
                 from /content/LightGBM/src/treelearner/gpu_tree_learner.h:33,
                 from /content/LightGBM/src/treelearner/parallel_tree_learner.h:16,
                 from /content/LightGBM/src/treelearner/data_parallel_tree_learner.cpp:9:
/usr/include/CL/cl_version.h:22:104: note: ‘#pragma message: cl_version.h: CL_TARGET_OPENCL_VERSION is not defined. Defaulting to 300 (OpenCL 3.0)’
   22 | #pragma message("cl_version.h: CL_TARGET_OPENCL_VERSION is not defined. Defaulting to 300 (OpenCL 3.0)")
      |                                                                                                        ^
In file included from /usr/include/CL/cl.h:20,
                 from /content/LightGBM/external_libs/compute/include/boost/compute/cl.hpp:19,
                 from /content/LightGBM/external_libs/compute/include/boost/compute/config.hpp:16,
                 from /content/LightGBM/external_libs/compute/include/boost/compute/buffer.hpp:14,
                 from /content/LightGBM/external_libs/compute/include/boost/compute/core.hpp:18,
                 from /content/LightGBM/src/treelearner/gpu_tree_learner.h:33,
                 from /content/LightGBM/src/treelearner/parallel_tree_learner.h:16,
                 from /content/LightGBM/src/treelearner/feature_parallel_tree_learner.cpp:8:
/usr/include/CL/cl_version.h:22:104: note: ‘#pragma message: cl_version.h: CL_TARGET_OPENCL_VERSION is not defined. Defaulting to 300 (OpenCL 3.0)’
   22 | #pragma message("cl_version.h: CL_TARGET_OPENCL_VERSION is not defined. Defaulting to 300 (OpenCL 3.0)")
      |                                                                                                        ^
In file included from /usr/include/boost/smart_ptr/detail/sp_thread_sleep.hpp:22,
                 from /usr/include/boost/smart_ptr/detail/yield_k.hpp:23,
                 from /usr/include/boost/smart_ptr/detail/spinlock_gcc_atomic.hpp:14,
                 from /usr/include/boost/smart_ptr/detail/spinlock.hpp:42,
                 from /usr/include/boost/smart_ptr/detail/spinlock_pool.hpp:25,
                 from /usr/include/boost/smart_ptr/shared_ptr.hpp:29,
                 from /usr/include/boost/shared_ptr.hpp:17,
                 from /content/LightGBM/external_libs/compute/include/boost/compute/utility/program_cache.hpp:17,
                 from /content/LightGBM/external_libs/compute/include/boost/compute/detail/meta_kernel.hpp:40,
                 from /content/LightGBM/external_libs/compute/include/boost/compute/types/complex.hpp:20,
                 from /content/LightGBM/external_libs/compute/include/boost/compute/types.hpp:18,
                 from /content/LightGBM/external_libs/compute/include/boost/compute/core.hpp:25,
                 from /content/LightGBM/src/treelearner/gpu_tree_learner.h:33,
                 from /content/LightGBM/src/treelearner/parallel_tree_learner.h:16,
                 from /content/LightGBM/src/treelearner/data_parallel_tree_learner.cpp:9:
/usr/include/boost/bind.hpp:36:1: note: ‘#pragma message: The practice of declaring the Bind placeholders (_1, _2, ...) in the global namespace is deprecated. Please use <boost/bind/bind.hpp> + using namespace boost::placeholders, or define BOOST_BIND_GLOBAL_PLACEHOLDERS to retain the current behavior.’
   36 | BOOST_PRAGMA_MESSAGE(
      | ^~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/boost/smart_ptr/detail/sp_thread_sleep.hpp:22,
                 from /usr/include/boost/smart_ptr/detail/yield_k.hpp:23,
                 from /usr/include/boost/smart_ptr/detail/spinlock_gcc_atomic.hpp:14,
                 from /usr/include/boost/smart_ptr/detail/spinlock.hpp:42,
                 from /usr/include/boost/smart_ptr/detail/spinlock_pool.hpp:25,
                 from /usr/include/boost/smart_ptr/shared_ptr.hpp:29,
                 from /usr/include/boost/shared_ptr.hpp:17,
                 from /content/LightGBM/external_libs/compute/include/boost/compute/utility/program_cache.hpp:17,
                 from /content/LightGBM/external_libs/compute/include/boost/compute/detail/meta_kernel.hpp:40,
                 from /content/LightGBM/external_libs/compute/include/boost/compute/types/complex.hpp:20,
                 from /content/LightGBM/external_libs/compute/include/boost/compute/types.hpp:18,
                 from /content/LightGBM/external_libs/compute/include/boost/compute/core.hpp:25,
                 from /content/LightGBM/src/treelearner/gpu_tree_learner.h:33,
                 from /content/LightGBM/src/treelearner/parallel_tree_learner.h:16,
                 from /content/LightGBM/src/treelearner/feature_parallel_tree_learner.cpp:8:
/usr/include/boost/bind.hpp:36:1: note: ‘#pragma message: The practice of declaring the Bind placeholders (_1, _2, ...) in the global namespace is deprecated. Please use <boost/bind/bind.hpp> + using namespace boost::placeholders, or define BOOST_BIND_GLOBAL_PLACEHOLDERS to retain the current behavior.’
   36 | BOOST_PRAGMA_MESSAGE(
      | ^~~~~~~~~~~~~~~~~~~~
[ 52%] Building CXX object CMakeFiles/_lightgbm.dir/src/treelearner/gpu_tree_learner.cpp.o
[ 53%] Building CXX object CMakeFiles/_lightgbm.dir/src/treelearner/linear_tree_learner.cpp.o
In file included from /usr/include/CL/cl.h:20,
                 from /content/LightGBM/external_libs/compute/include/boost/compute/cl.hpp:19,
                 from /content/LightGBM/external_libs/compute/include/boost/compute/config.hpp:16,
                 from /content/LightGBM/external_libs/compute/include/boost/compute/buffer.hpp:14,
                 from /content/LightGBM/external_libs/compute/include/boost/compute/core.hpp:18,
                 from /content/LightGBM/src/treelearner/gpu_tree_learner.h:33,
                 from /content/LightGBM/src/treelearner/gpu_tree_learner.cpp:7:
/usr/include/CL/cl_version.h:22:104: note: ‘#pragma message: cl_version.h: CL_TARGET_OPENCL_VERSION is not defined. Defaulting to 300 (OpenCL 3.0)’
   22 | #pragma message("cl_version.h: CL_TARGET_OPENCL_VERSION is not defined. Defaulting to 300 (OpenCL 3.0)")
      |                                                                                                        ^
[ 55%] Building CXX object CMakeFiles/_lightgbm.dir/src/treelearner/serial_tree_learner.cpp.o
In file included from /usr/include/boost/smart_ptr/detail/sp_thread_sleep.hpp:22,
                 from /usr/include/boost/smart_ptr/detail/yield_k.hpp:23,
                 from /usr/include/boost/smart_ptr/detail/spinlock_gcc_atomic.hpp:14,
                 from /usr/include/boost/smart_ptr/detail/spinlock.hpp:42,
                 from /usr/include/boost/smart_ptr/detail/spinlock_pool.hpp:25,
                 from /usr/include/boost/smart_ptr/shared_ptr.hpp:29,
                 from /usr/include/boost/shared_ptr.hpp:17,
                 from /content/LightGBM/external_libs/compute/include/boost/compute/utility/program_cache.hpp:17,
                 from /content/LightGBM/external_libs/compute/include/boost/compute/detail/meta_kernel.hpp:40,
                 from /content/LightGBM/external_libs/compute/include/boost/compute/types/complex.hpp:20,
                 from /content/LightGBM/external_libs/compute/include/boost/compute/types.hpp:18,
                 from /content/LightGBM/external_libs/compute/include/boost/compute/core.hpp:25,
                 from /content/LightGBM/src/treelearner/gpu_tree_learner.h:33,
                 from /content/LightGBM/src/treelearner/gpu_tree_learner.cpp:7:
/usr/include/boost/bind.hpp:36:1: note: ‘#pragma message: The practice of declaring the Bind placeholders (_1, _2, ...) in the global namespace is deprecated. Please use <boost/bind/bind.hpp> + using namespace boost::placeholders, or define BOOST_BIND_GLOBAL_PLACEHOLDERS to retain the current behavior.’
   36 | BOOST_PRAGMA_MESSAGE(
      | ^~~~~~~~~~~~~~~~~~~~
[ 56%] Building CXX object CMakeFiles/lightgbm.dir/src/io/config.cpp.o
[ 57%] Building CXX object CMakeFiles/lightgbm.dir/src/io/config_auto.cpp.o
[ 59%] Building CXX object CMakeFiles/lightgbm.dir/src/io/dataset.cpp.o
[ 60%] Building CXX object CMakeFiles/_lightgbm.dir/src/treelearner/tree_learner.cpp.o
[ 62%] Building CXX object CMakeFiles/_lightgbm.dir/src/treelearner/voting_parallel_tree_learner.cpp.o
In file included from /usr/include/CL/cl.h:20,
                 from /content/LightGBM/external_libs/compute/include/boost/compute/cl.hpp:19,
                 from /content/LightGBM/external_libs/compute/include/boost/compute/config.hpp:16,
                 from /content/LightGBM/external_libs/compute/include/boost/compute/buffer.hpp:14,
                 from /content/LightGBM/external_libs/compute/include/boost/compute/core.hpp:18,
                 from /content/LightGBM/src/treelearner/gpu_tree_learner.h:33,
                 from /content/LightGBM/src/treelearner/tree_learner.cpp:8:
/usr/include/CL/cl_version.h:22:104: note: ‘#pragma message: cl_version.h: CL_TARGET_OPENCL_VERSION is not defined. Defaulting to 300 (OpenCL 3.0)’
   22 | #pragma message("cl_version.h: CL_TARGET_OPENCL_VERSION is not defined. Defaulting to 300 (OpenCL 3.0)")
      |                                                                                                        ^
In file included from /usr/include/CL/cl.h:20,
                 from /content/LightGBM/external_libs/compute/include/boost/compute/cl.hpp:19,
                 from /content/LightGBM/external_libs/compute/include/boost/compute/config.hpp:16,
                 from /content/LightGBM/external_libs/compute/include/boost/compute/buffer.hpp:14,
                 from /content/LightGBM/external_libs/compute/include/boost/compute/core.hpp:18,

In [1]:
!pip uninstall -y lightgbm
!rm -rf /content/LightGBM
!pip install lightgbm

Found existing installation: lightgbm 4.5.0
Uninstalling lightgbm-4.5.0:
  Successfully uninstalled lightgbm-4.5.0
Collecting lightgbm
  Downloading lightgbm-4.6.0-py3-none-manylinux_2_28_x86_64.whl.metadata (17 kB)
Requirement already satisfied: numpy>=1.17.0 in /usr/local/lib/python3.11/dist-packages (from lightgbm) (2.0.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.11/dist-packages (from lightgbm) (1.15.3)
Downloading lightgbm-4.6.0-py3-none-manylinux_2_28_x86_64.whl (3.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.6/3.6 MB 70.1 MB/s eta 0:00:00
Installing collected packages: lightgbm
Successfully installed lightgbm-4.6.0

In [2]:
# 설치 확인
import lightgbm as lgb
print(lgb.__version__)

4.6.0

In [3]:
!pip install optuna

Collecting optuna
  Downloading optuna-4.4.0-py3-none-any.whl.metadata (17 kB)
Collecting alembic>=1.5.0 (from optuna)
  Downloading alembic-1.16.2-py3-none-any.whl.metadata (7.3 kB)
Collecting colorlog (from optuna)
  Downloading colorlog-6.9.0-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.11/dist-packages (from optuna) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from optuna) (24.2)
Requirement already satisfied: sqlalchemy>=1.4.2 in /usr/local/lib/python3.11/dist-packages (from optuna) (2.0.41)
Requirement already satisfied: tqdm in /usr/local/lib/python3.11/dist-packages (from optuna) (4.67.1)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.11/dist-packages (from optuna) (6.0.2)
Requirement already satisfied: Mako in /usr/lib/python3/dist-packages (from alembic>=1.5.0->optuna) (1.1.3)
Requirement already satisfied: typing-extensions>=4.12 in /usr/local/lib/python3.11/dist-packages (from alembic>=1.5.0->optuna) (4.14.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.11/dist-packages (from sqlalchemy>=1.4.2->optuna) (3.2.3)
Downloading optuna-4.4.0-py3-none-any.whl (395 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 395.9/395.9 kB 17.4 MB/s eta 0:00:00
Downloading alembic-1.16.2-py3-none-any.whl (242 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 242.7/242.7 kB 18.4 MB/s eta 0:00:00
Downloading colorlog-6.9.0-py3-none-any.whl (11 kB)
Installing collected packages: colorlog, alembic, optuna
Successfully installed alembic-1.16.2 colorlog-6.9.0 optuna-4.4.0

In [5]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import optuna
import os
import lightgbm as lgb

import seaborn as sns
import matplotlib.pyplot as plt
import matplotlib.font_manager as fm
from sklearn.metrics import accuracy_score

# 경고 뜨지 않게 설정
import warnings
warnings.filterwarnings('ignore')

# 그래프 설정
sns.set()

# 그래프 기본 설정
plt.rcParams['font.family'] = 'NanumGothic'
# plt.rcParams['font.family'] = 'AppleGothic'
plt.rcParams['figure.figsize'] = 12, 6
plt.rcParams['font.size'] = 14
plt.rcParams['axes.unicode_minus'] = False

In [6]:
# 데이터 경로
print(os.getcwd())
path = '/content/drive/MyDrive/파이널 프로젝트/2025_07_07/'
print(os.listdir(path))

/content
['Segment_merge_ver_05.parquet', 'Segment_merge_test_ver_05.parquet']

In [7]:
train = pd.read_parquet(path + 'Segment_merge_ver_05.parquet')

In [8]:
test = pd.read_parquet(path +'Segment_merge_test_ver_05.parquet' ) # 기준년월, ID 컬럼 삭제된 파일

In [9]:
print(train.shape)
print(test.shape)

(2400000, 138)
(600000, 137)

In [10]:
drop_cols = ['기준년월','ID','Segment']
x = train.drop(columns=drop_cols)
y = train['Segment']

In [11]:
# 데이터 분할
X_tr, X_val, y_tr, y_val = train_test_split(x, y, test_size=0.2, random_state=42, stratify=y)

# x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [12]:
# # 파라미터 값 조정
# def objective(trial):
#     param = {
#         'objective': 'multiclass',
#         'num_class': 5,
#         'metric': 'multi_logloss',
#         'verbosity': -1,
#         'boosting_type': 'gbdt',
#         'learning_rate': trial.suggest_float('learning_rate', 0.05, 0.12),  # 좁힘
#         'num_leaves': trial.suggest_int('num_leaves', 150, 250),           # 좁힘
#         'max_depth': trial.suggest_int('max_depth', 10, 15),               # 최적값에 집중
#         'min_child_samples': trial.suggest_int('min_child_samples', 20, 50),
#         'subsample': trial.suggest_float('subsample', 0.8, 0.95),
#         'colsample_bytree': trial.suggest_float('colsample_bytree', 0.7, 0.9),
#         'reg_alpha': trial.suggest_float('reg_alpha', 1e-4, 1.0, log=True), # 과도한 제약 제거
#         'reg_lambda': trial.suggest_float('reg_lambda', 1e-5, 0.1, log=True),
#         'n_estimators': 1000,
#         'random_state': 42,
#         'n_jobs': -1,
#          'device_type':'gpu'
#     }

#     model = lgb.LGBMClassifier(**param)

#     model.fit(
#         X_tr, y_tr,
#         eval_set=[(X_val, y_val)],
#         eval_metric='multi_logloss',
#         callbacks=[lgb.early_stopping(50, verbose=False)],
#     )

#     preds = model.predict(X_val)
#     acc = accuracy_score(y_val, preds)
#     return acc

#     [W 2025-07-07 06:35:57,773] Trial 10 failed with parameters: {'learning_rate': 0.08290312337050593, 'num_leaves': 207, 'max_depth': 11, 'min_child_samples': 48, 'subsample': 0.9441386022205047, 'colsample_bytree': 0.8781227616631291, 'reg_alpha': 0.4168762731451913, 'reg_lambda': 2.999104616193986e-05} because of the following error: LightGBMError('Check failed: (best_split_info.left_count) > (0) at /tmp/lightgbm/LightGBM/lightgbm-python/src/treelearner/serial_tree_learner.cpp, line 846 .\n').
# Traceback (most recent call last):
#   File "/usr/local/lib/python3.11/dist-packages/optuna/study/_optimize.py", line 201, in _run_trial
#     value_or_values = func(trial)
#                       ^^^^^^^^^^^
#   File "/tmp/ipython-input-11-1016100464.py", line 25, in objective
#     model.fit(
#   File "/usr/local/lib/python3.11/dist-packages/lightgbm/sklearn.py", line 1284, in fit
#     super().fit(
#   File "/usr/local/lib/python3.11/dist-packages/lightgbm/sklearn.py", line 955, in fit
#     self._Booster = train(
#                     ^^^^^^
#   File "/usr/local/lib/python3.11/dist-packages/lightgbm/engine.py", line 307, in train
#     booster.update(fobj=fobj)
#   File "/usr/local/lib/python3.11/dist-packages/lightgbm/basic.py", line 4135, in update
#     _safe_call(
#   File "/usr/local/lib/python3.11/dist-packages/lightgbm/basic.py", line 296, in _safe_call
#     raise LightGBMError(_LIB.LGBM_GetLastError().decode("utf-8"))
# lightgbm.basic.LightGBMError: Check failed: (best_split_info.left_count) > (0) at /tmp/lightgbm/LightGBM/lightgbm-python/src/treelearner/serial_tree_learner.cpp, line 846 .

In [16]:
# objective 함수 정의
def objective(trial):
  param = {
    'objective': 'multiclass',
    'num_class': 5,
    'metric': 'multi_logloss',
    'verbosity': -1,
    'boosting_type': 'gbdt',
    'learning_rate': trial.suggest_float('learning_rate', 0.01, 0.1),
    'num_leaves': trial.suggest_int('num_leaves', 31, 128),            # 최대값 축소 (과도한 복잡도 방지)
    'max_depth': trial.suggest_int('max_depth', 7, 20),                # 최소값 조금 올림, 최대값 축소
    'min_child_samples': trial.suggest_int('min_child_samples', 20, 50),# 최소값 줄여서 분할 가능성 증가
    'subsample': trial.suggest_float('subsample', 0.7, 1.0),           # 기본값 유지하거나 조금 좁히기
    'colsample_bytree': trial.suggest_float('colsample_bytree', 0.7, 1.0),
    'reg_alpha': trial.suggest_float('reg_alpha', 1e-8, 1.0, log=True),  # 너무 큰 값 제외
    'reg_lambda': trial.suggest_float('reg_lambda', 1e-8, 1.0, log=True),
    'n_estimators': 1000,
    'random_state': 42,
    'n_jobs': -1
}
  model = lgb.LGBMClassifier(**param,verbose=1)

  model.fit(
        X_tr, y_tr,
        eval_set=[(X_val, y_val)],
        eval_metric='multi_logloss',
        callbacks=[lgb.early_stopping(50, verbose=False)],
    )

  preds = model.predict(X_val)
  acc = accuracy_score(y_val, preds)
  return acc  # maximize accuracy

In [19]:
study = optuna.create_study(direction='maximize')

# # 예시: 병렬 실행 (최대 4개 프로세스)
# optuna.study.create_study(direction='maximize')
# study.optimize(objective, n_trials=50, n_jobs=4)

[I 2025-07-08 00:18:49,728] A new study created in memory with name: no-name-32c5f4ac-5d19-428a-bf23-b825978c1044

ver.03파일은 에러가나서 분석 중단
병렬 처리를 해서 에러가나나...? <br>
params 값 범위 조정 X + n_jobs 옵션 X 실행해봄 <br>
에러가 발생하는 주 원인 중 하나는 min_child_samples가 너무 크거나, num_leaves와 max_depth 조합이 적절하지 않아서 분할 시 왼쪽 자식 노드에 데이터가 없을 때입니다.

In [20]:
study.optimize(objective, n_trials=30)

print("Best trial:")
print(" Value: ", study.best_value)
print(" Params: ")

[I 2025-07-08 00:20:29,324] Trial 0 finished with value: 0.88664375 and parameters: {'learning_rate': 0.07466701696176672, 'num_leaves': 36, 'max_depth': 15, 'min_child_samples': 42, 'subsample': 0.7322354108006245, 'colsample_bytree': 0.992485321261734, 'reg_alpha': 0.02382648722197509, 'reg_lambda': 2.9005835528991715e-05}. Best is trial 0 with value: 0.88664375.
[I 2025-07-08 00:36:14,141] Trial 1 finished with value: 0.93765 and parameters: {'learning_rate': 0.07908925401862119, 'num_leaves': 119, 'max_depth': 9, 'min_child_samples': 41, 'subsample': 0.8365979872487723, 'colsample_bytree': 0.9170262821764648, 'reg_alpha': 0.008998855108257963, 'reg_lambda': 7.003764272106548e-06}. Best is trial 1 with value: 0.93765.
[I 2025-07-08 00:37:54,806] Trial 2 finished with value: 0.89005 and parameters: {'learning_rate': 0.08635816013953589, 'num_leaves': 54, 'max_depth': 14, 'min_child_samples': 46, 'subsample': 0.9313315725594427, 'colsample_bytree': 0.8238908678585743, 'reg_alpha': 0.06283094207864365, 'reg_lambda': 1.0945054001750718e-07}. Best is trial 1 with value: 0.93765.
[I 2025-07-08 00:43:27,309] Trial 3 finished with value: 0.90589375 and parameters: {'learning_rate': 0.04582916560761264, 'num_leaves': 69, 'max_depth': 16, 'min_child_samples': 27, 'subsample': 0.8906451044910053, 'colsample_bytree': 0.8460364943002381, 'reg_alpha': 3.7640236977028215e-06, 'reg_lambda': 7.291033873506792e-07}. Best is trial 1 with value: 0.93765.
[I 2025-07-08 01:04:48,139] Trial 4 finished with value: 0.91363125 and parameters: {'learning_rate': 0.015247597637197623, 'num_leaves': 91, 'max_depth': 7, 'min_child_samples': 24, 'subsample': 0.8187499371333938, 'colsample_bytree': 0.9215846022609102, 'reg_alpha': 0.0006988078147391942, 'reg_lambda': 2.3982085877696635e-08}. Best is trial 1 with value: 0.93765.
[I 2025-07-08 01:18:23,783] Trial 5 finished with value: 0.9224708333333334 and parameters: {'learning_rate': 0.0764291566520831, 'num_leaves': 32, 'max_depth': 8, 'min_child_samples': 33, 'subsample': 0.7292401122995112, 'colsample_bytree': 0.8982122971660046, 'reg_alpha': 1.688330182165889e-05, 'reg_lambda': 0.0006773920994422463}. Best is trial 1 with value: 0.93765.
[I 2025-07-08 01:21:11,093] Trial 6 finished with value: 0.90110625 and parameters: {'learning_rate': 0.09436325628536336, 'num_leaves': 99, 'max_depth': 10, 'min_child_samples': 39, 'subsample': 0.868041581098788, 'colsample_bytree': 0.9727497562979368, 'reg_alpha': 0.11223130141839006, 'reg_lambda': 2.9641997122164845e-05}. Best is trial 1 with value: 0.93765.
[I 2025-07-08 01:40:02,069] Trial 7 finished with value: 0.9374020833333333 and parameters: {'learning_rate': 0.05931692448887698, 'num_leaves': 119, 'max_depth': 10, 'min_child_samples': 23, 'subsample': 0.8155736313822586, 'colsample_bytree': 0.8939746963785961, 'reg_alpha': 0.9982928384917052, 'reg_lambda': 0.02354041909126295}. Best is trial 1 with value: 0.93765.
[I 2025-07-08 02:03:46,297] Trial 8 finished with value: 0.9159520833333333 and parameters: {'learning_rate': 0.015338760212427638, 'num_leaves': 91, 'max_depth': 13, 'min_child_samples': 36, 'subsample': 0.9327413571184725, 'colsample_bytree': 0.8012249077927208, 'reg_alpha': 0.13046364096023483, 'reg_lambda': 3.5242315374803314e-08}. Best is trial 1 with value: 0.93765.
[I 2025-07-08 02:05:12,491] Trial 9 finished with value: 0.88785625 and parameters: {'learning_rate': 0.08489854239597623, 'num_leaves': 42, 'max_depth': 12, 'min_child_samples': 26, 'subsample': 0.948257746601213, 'colsample_bytree': 0.831605967708356, 'reg_alpha': 1.0709211446339678e-08, 'reg_lambda': 5.707911134192387e-07}. Best is trial 1 with value: 0.93765.
[I 2025-07-08 02:25:26,488] Trial 10 finished with value: 0.9355916666666667 and parameters: {'learning_rate': 0.04569384025150704, 'num_leaves': 123, 'max_depth': 20, 'min_child_samples': 49, 'subsample': 0.9994738225254945, 'colsample_bytree': 0.7087501582263624, 'reg_alpha': 0.0007132630090920225, 'reg_lambda': 0.1087493582542399}. Best is trial 1 with value: 0.93765.
[I 2025-07-08 02:45:09,151] Trial 11 finished with value: 0.9388333333333333 and parameters: {'learning_rate': 0.0622120762404836, 'num_leaves': 124, 'max_depth': 10, 'min_child_samples': 32, 'subsample': 0.8034474416951443, 'colsample_bytree': 0.9142574830559277, 'reg_alpha': 0.49675969786243485, 'reg_lambda': 0.9549173815968505}. Best is trial 11 with value: 0.9388333333333333.
[I 2025-07-08 03:04:42,493] Trial 12 finished with value: 0.93579375 and parameters: {'learning_rate': 0.05959255620551049, 'num_leaves': 110, 'max_depth': 10, 'min_child_samples': 32, 'subsample': 0.7943989156359261, 'colsample_bytree': 0.9478161490763608, 'reg_alpha': 0.002607733847886403, 'reg_lambda': 0.0016861664340607366}. Best is trial 11 with value: 0.9388333333333333.
[I 2025-07-08 03:25:45,865] Trial 13 finished with value: 0.9390541666666666 and parameters: {'learning_rate': 0.0699999158849763, 'num_leaves': 127, 'max_depth': 9, 'min_child_samples': 41, 'subsample': 0.7718587793461152, 'colsample_bytree': 0.8761257841357446, 'reg_alpha': 0.884408127930731, 'reg_lambda': 5.744666561451077e-06}. Best is trial 13 with value: 0.9390541666666666.
[I 2025-07-08 03:42:50,134] Trial 14 finished with value: 0.9407291666666666 and parameters: {'learning_rate': 0.06487248227151199, 'num_leaves': 127, 'max_depth': 11, 'min_child_samples': 29, 'subsample': 0.7734858236793587, 'colsample_bytree': 0.7560965960654966, 'reg_alpha': 0.9498311768193832, 'reg_lambda': 0.3457309574651247}. Best is trial 14 with value: 0.9407291666666666.
[I 2025-07-08 03:48:39,811] Trial 15 finished with value: 0.90745 and parameters: {'learning_rate': 0.04720198802258427, 'num_leaves': 107, 'max_depth': 12, 'min_child_samples': 20, 'subsample': 0.767080434855501, 'colsample_bytree': 0.7664763905702974, 'reg_alpha': 3.071865463932719e-07, 'reg_lambda': 0.000483434597172415}. Best is trial 14 with value: 0.9407291666666666.
[I 2025-07-08 04:07:48,180] Trial 16 finished with value: 0.9214458333333333 and parameters: {'learning_rate': 0.02957871617490395, 'num_leaves': 69, 'max_depth': 17, 'min_child_samples': 29, 'subsample': 0.7572564466813165, 'colsample_bytree': 0.7444267389502701, 'reg_alpha': 0.00014402508618858008, 'reg_lambda': 0.0077827475538361605}. Best is trial 14 with value: 0.9407291666666666.
[I 2025-07-08 04:24:19,160] Trial 17 finished with value: 0.9332020833333333 and parameters: {'learning_rate': 0.06898823376479858, 'num_leaves': 108, 'max_depth': 7, 'min_child_samples': 37, 'subsample': 0.7093988312429526, 'colsample_bytree': 0.8753622268978954, 'reg_alpha': 0.7008082963938765, 'reg_lambda': 4.018654341675846e-06}. Best is trial 14 with value: 0.9407291666666666.
[I 2025-07-08 04:42:32,086] Trial 18 finished with value: 0.9471354166666667 and parameters: {'learning_rate': 0.09968074420540968, 'num_leaves': 127, 'max_depth': 12, 'min_child_samples': 44, 'subsample': 0.7803826377746543, 'colsample_bytree': 0.7943406603089208, 'reg_alpha': 0.008330746123943621, 'reg_lambda': 0.6228954923795628}. Best is trial 18 with value: 0.9471354166666667.
[I 2025-07-08 04:59:19,945] Trial 19 finished with value: 0.9399104166666666 and parameters: {'learning_rate': 0.09733712655696192, 'num_leaves': 81, 'max_depth': 12, 'min_child_samples': 46, 'subsample': 0.8553616177251547, 'colsample_bytree': 0.7870634563610954, 'reg_alpha': 0.008672345945828504, 'reg_lambda': 0.6635224428832768}. Best is trial 18 with value: 0.9471354166666667.
[I 2025-07-08 05:19:39,119] Trial 20 finished with value: 0.9295854166666667 and parameters: {'learning_rate': 0.033086471749758595, 'num_leaves': 114, 'max_depth': 19, 'min_child_samples': 49, 'subsample': 0.7832711828357227, 'colsample_bytree': 0.7005950777427481, 'reg_alpha': 0.001984138540356724, 'reg_lambda': 0.07927391442852025}. Best is trial 18 with value: 0.9471354166666667.
[I 2025-07-08 05:34:40,157] Trial 21 finished with value: 0.9397541666666667 and parameters: {'learning_rate': 0.09878569096800052, 'num_leaves': 79, 'max_depth': 12, 'min_child_samples': 45, 'subsample': 0.8706782306640335, 'colsample_bytree': 0.7816345419240031, 'reg_alpha': 0.007387120297369693, 'reg_lambda': 0.8167890629077322}. Best is trial 18 with value: 0.9471354166666667.
[I 2025-07-08 05:50:20,584] Trial 22 finished with value: 0.9419416666666667 and parameters: {'learning_rate': 0.08875657492229536, 'num_leaves': 99, 'max_depth': 13, 'min_child_samples': 46, 'subsample': 0.8425500090513901, 'colsample_bytree': 0.742161484592134, 'reg_alpha': 9.1920815113892e-05, 'reg_lambda': 0.19533993491551993}. Best is trial 18 with value: 0.9471354166666667.
[I 2025-07-08 06:07:19,327] Trial 23 finished with value: 0.9417979166666667 and parameters: {'learning_rate': 0.0878716991116855, 'num_leaves': 100, 'max_depth': 14, 'min_child_samples': 50, 'subsample': 0.7418659198866758, 'colsample_bytree': 0.7405770735189854, 'reg_alpha': 4.889957480166548e-05, 'reg_lambda': 0.1452489665824174}. Best is trial 18 with value: 0.9471354166666667.
[I 2025-07-08 06:21:44,219] Trial 24 finished with value: 0.9418125 and parameters: {'learning_rate': 0.08953385248347644, 'num_leaves': 97, 'max_depth': 14, 'min_child_samples': 50, 'subsample': 0.7438877809961554, 'colsample_bytree': 0.7317456699934817, 'reg_alpha': 3.991247040466439e-05, 'reg_lambda': 0.008956780863549757}. Best is trial 18 with value: 0.9471354166666667.
[I 2025-07-08 06:36:07,849] Trial 25 finished with value: 0.9420791666666667 and parameters: {'learning_rate': 0.09233914906006208, 'num_leaves': 96, 'max_depth': 17, 'min_child_samples': 44, 'subsample': 0.70234587995067, 'colsample_bytree': 0.7276146844274561, 'reg_alpha': 2.843625786633033e-06, 'reg_lambda': 0.02019333445402454}. Best is trial 18 with value: 0.9471354166666667.
[I 2025-07-08 06:50:23,165] Trial 26 finished with value: 0.9379604166666666 and parameters: {'learning_rate': 0.08179016645886623, 'num_leaves': 84, 'max_depth': 18, 'min_child_samples': 43, 'subsample': 0.7012032926287645, 'colsample_bytree': 0.7206336612785409, 'reg_alpha': 1.49713362473061e-06, 'reg_lambda': 0.015302832845070165}. Best is trial 18 with value: 0.9471354166666667.
[I 2025-07-08 07:04:29,901] Trial 27 finished with value: 0.9344854166666666 and parameters: {'learning_rate': 0.09492356139033614, 'num_leaves': 59, 'max_depth': 16, 'min_child_samples': 44, 'subsample': 0.895379898552614, 'colsample_bytree': 0.808187616264757, 'reg_alpha': 5.4753392331400985e-08, 'reg_lambda': 0.04577483204844862}. Best is trial 18 with value: 0.9471354166666667.
[I 2025-07-08 07:13:29,179] Trial 28 finished with value: 0.9293020833333333 and parameters: {'learning_rate': 0.09987672429701464, 'num_leaves': 104, 'max_depth': 15, 'min_child_samples': 47, 'subsample': 0.8382974129606977, 'colsample_bytree': 0.767749670405347, 'reg_alpha': 6.427042710067544e-06, 'reg_lambda': 0.0035571311342106706}. Best is trial 18 with value: 0.9471354166666667.
[I 2025-07-08 07:24:46,797] Trial 29 finished with value: 0.93145 and parameters: {'learning_rate': 0.09096943239172758, 'num_leaves': 93, 'max_depth': 15, 'min_child_samples': 39, 'subsample': 0.7224091289801957, 'colsample_bytree': 0.7281338652499518, 'reg_alpha': 0.00023926937039777608, 'reg_lambda': 0.00016242271959490467}. Best is trial 18 with value: 0.9471354166666667.

Best trial:
 Value:  0.9471354166666667
 Params:

In [ ]:
# print(model.get_params()['device_type']) #gpu 사용여부

In [21]:
# 최적 파라미터로 전체 학습
best_params = study.best_params

final_model = lgb.LGBMClassifier(**best_params)
# X_tr, X_val, y_tr, y_val
final_model.fit( X_tr, y_tr)

LGBMClassifier(colsample_bytree=0.7943406603089208,
               learning_rate=0.09968074420540968, max_depth=12,
               min_child_samples=44, num_leaves=127,
               reg_alpha=0.008330746123943621, reg_lambda=0.6228954923795628,
               subsample=0.7803826377746543)

In [29]:
import pickle
pickle.dump(final_model, open('/content/drive/MyDrive/Colab_Notebooks/LGBM_model.pkl', 'wb'))

In [30]:
print(os.getcwd())

/content

In [31]:
X_test = test.drop(columns=['기준년월','ID'])

In [32]:
## 예측
# 5. 예측 수행
final_pred = final_model.predict(X_test)               # 예측 레이블
final_proba = final_model.predict_proba(X_test)

In [33]:
# 6. 결과 저장
res_df = pd.DataFrame({
    'ID': test.ID,
    'Segment': final_pred
})

In [35]:
res_df.to_csv('/content/drive/MyDrive/Colab_Notebooks/hyper_pred_ver_05_result.csv')

In [34]:
representative_segments = (
    res_df.groupby('ID')['Segment']
    .agg(lambda x: x.mode().iloc[0])  # mode()는 여러 개일 수 있어 .iloc[0]으로 하나 선택
    .reset_index()
    .rename(columns={'Segment': 'Segment'})
)

print(representative_segments)

               ID Segment
0      TEST_00000       E
1      TEST_00001       E
2      TEST_00002       E
3      TEST_00003       E
4      TEST_00004       E
...           ...     ...
99995  TEST_99995       E
99996  TEST_99996       E
99997  TEST_99997       E
99998  TEST_99998       C
99999  TEST_99999       E

[100000 rows x 2 columns]

In [36]:
representative_segments.shape

(100000, 2)

In [37]:
representative_segments.to_csv('/content/drive/MyDrive/Colab_Notebooks/hyper_pred_ver_05_Segment.csv',index=False)

전처리 ver.02 파일 하이퍼 파라미터 코드 및 결과

In [ ]:
# # objective 함수 정의
# def objective(trial):
#     param = {
#         'objective': 'multiclass',
#         'num_class': 5,
#         'metric': 'multi_logloss',
#         'verbosity': -1,
#         'boosting_type': 'gbdt',
#         'learning_rate': trial.suggest_float('learning_rate', 0.01, 0.1),
#         'num_leaves': trial.suggest_int('num_leaves', 31, 256),
#         'max_depth': trial.suggest_int('max_depth', 3, 15),
#         'min_child_samples': trial.suggest_int('min_child_samples', 10, 100),
#         'subsample': trial.suggest_float('subsample', 0.6, 1.0),
#         'colsample_bytree': trial.suggest_float('colsample_bytree', 0.6, 1.0),
#         'reg_alpha': trial.suggest_float('reg_alpha', 1e-8, 10.0, log=True),
#         'reg_lambda': trial.suggest_float('reg_lambda', 1e-8, 10.0, log=True),
#         'n_estimators': 1000,
#         'random_state': 42,
#         'n_jobs': -1
#     }

#     model = lgb.LGBMClassifier(**param)

#     model.fit(
#         X_tr, y_tr,
#         eval_set=[(X_val, y_val)],
#         eval_metric='multi_logloss',
#         callbacks=[lgb.early_stopping(50, verbose=False)],
#     )

#     preds = model.predict(X_val)
#     acc = accuracy_score(y_val, preds)
#     return acc  # maximize accuracy

In [ ]:
study = optuna.create_study(direction='maximize')

[I 2025-07-04 02:20:24,179] A new study created in memory with name: no-name-3ca0ddd9-adfb-49e4-8f40-5ae5c47a3614

In [ ]:
study.optimize(objective, n_trials=30)

print("Best trial:")
print(" Value: ", study.best_value)
print(" Params: ")

[I 2025-07-04 02:30:29,848] Trial 0 finished with value: 0.883425 and parameters: {'learning_rate': 0.034638243239393386, 'num_leaves': 170, 'max_depth': 3, 'min_child_samples': 56, 'subsample': 0.9998793510407011, 'colsample_bytree': 0.9598155319199569, 'reg_alpha': 2.027879221439409e-07, 'reg_lambda': 4.236926716050374e-06}. Best is trial 0 with value: 0.883425.
[I 2025-07-04 02:35:21,008] Trial 1 finished with value: 0.89506875 and parameters: {'learning_rate': 0.05494596683922364, 'num_leaves': 202, 'max_depth': 13, 'min_child_samples': 81, 'subsample': 0.6781913086860935, 'colsample_bytree': 0.7930060051856186, 'reg_alpha': 8.763968689532738e-05, 'reg_lambda': 8.304535294271677e-08}. Best is trial 1 with value: 0.89506875.
[I 2025-07-04 02:43:02,976] Trial 2 finished with value: 0.8830145833333334 and parameters: {'learning_rate': 0.030554750786629677, 'num_leaves': 176, 'max_depth': 3, 'min_child_samples': 27, 'subsample': 0.6177858184581875, 'colsample_bytree': 0.8063184697276666, 'reg_alpha': 0.008835451838785379, 'reg_lambda': 0.0002493421482247173}. Best is trial 1 with value: 0.89506875.
[I 2025-07-04 03:02:13,746] Trial 3 finished with value: 0.907125 and parameters: {'learning_rate': 0.018593116460803673, 'num_leaves': 233, 'max_depth': 13, 'min_child_samples': 41, 'subsample': 0.8806579111525072, 'colsample_bytree': 0.8891254169074612, 'reg_alpha': 2.4006599660100034e-06, 'reg_lambda': 3.0807133496811436e-05}. Best is trial 3 with value: 0.907125.
[I 2025-07-04 03:15:12,386] Trial 4 finished with value: 0.9121375 and parameters: {'learning_rate': 0.0859772970432883, 'num_leaves': 76, 'max_depth': 12, 'min_child_samples': 36, 'subsample': 0.7251296951647164, 'colsample_bytree': 0.6128291458902433, 'reg_alpha': 0.0033278182562240313, 'reg_lambda': 0.014918136530035968}. Best is trial 4 with value: 0.9121375.
[I 2025-07-04 03:30:16,397] Trial 5 finished with value: 0.9201395833333333 and parameters: {'learning_rate': 0.05681559127854916, 'num_leaves': 162, 'max_depth': 11, 'min_child_samples': 11, 'subsample': 0.8022957375781216, 'colsample_bytree': 0.6849711177039731, 'reg_alpha': 0.00312868361550236, 'reg_lambda': 3.302835660608632}. Best is trial 5 with value: 0.9201395833333333.
[I 2025-07-04 03:43:58,287] Trial 6 finished with value: 0.8948354166666667 and parameters: {'learning_rate': 0.04041190629728977, 'num_leaves': 227, 'max_depth': 6, 'min_child_samples': 68, 'subsample': 0.9078704091369114, 'colsample_bytree': 0.6002864368113201, 'reg_alpha': 3.421677894820083, 'reg_lambda': 0.8670717362681576}. Best is trial 5 with value: 0.9201395833333333.
[I 2025-07-04 03:56:38,182] Trial 7 finished with value: 0.9125416666666667 and parameters: {'learning_rate': 0.07026175596714897, 'num_leaves': 93, 'max_depth': 9, 'min_child_samples': 54, 'subsample': 0.9720765259797843, 'colsample_bytree': 0.8615498846032572, 'reg_alpha': 8.251477400918191e-08, 'reg_lambda': 1.8270706995729238e-08}. Best is trial 5 with value: 0.9201395833333333.
[I 2025-07-04 04:08:44,618] Trial 8 finished with value: 0.88904375 and parameters: {'learning_rate': 0.016903329414612287, 'num_leaves': 106, 'max_depth': 6, 'min_child_samples': 58, 'subsample': 0.7757232563566204, 'colsample_bytree': 0.996923272577866, 'reg_alpha': 1.7366497823583308e-08, 'reg_lambda': 0.06034487640265942}. Best is trial 5 with value: 0.9201395833333333.
[I 2025-07-04 04:10:08,957] Trial 9 finished with value: 0.8804770833333333 and parameters: {'learning_rate': 0.06991154122522877, 'num_leaves': 87, 'max_depth': 7, 'min_child_samples': 48, 'subsample': 0.7573057350360727, 'colsample_bytree': 0.9034914627693288, 'reg_alpha': 3.344473767760186e-07, 'reg_lambda': 3.177472031968923e-05}. Best is trial 5 with value: 0.9201395833333333.
[I 2025-07-04 04:19:32,074] Trial 10 finished with value: 0.9055479166666667 and parameters: {'learning_rate': 0.09974759885854134, 'num_leaves': 44, 'max_depth': 10, 'min_child_samples': 16, 'subsample': 0.8455238024612065, 'colsample_bytree': 0.714616723408887, 'reg_alpha': 0.6441527117056043, 'reg_lambda': 4.835133180263941}. Best is trial 5 with value: 0.9201395833333333.
[I 2025-07-04 04:22:13,631] Trial 11 finished with value: 0.8868020833333333 and parameters: {'learning_rate': 0.06417858025243912, 'num_leaves': 130, 'max_depth': 10, 'min_child_samples': 93, 'subsample': 0.9937568772515687, 'colsample_bytree': 0.7119415971770132, 'reg_alpha': 3.205175718152942e-05, 'reg_lambda': 3.258385352325438e-08}. Best is trial 5 with value: 0.9201395833333333.
[I 2025-07-04 04:33:13,715] Trial 12 finished with value: 0.9254208333333334 and parameters: {'learning_rate': 0.07611855328885889, 'num_leaves': 138, 'max_depth': 15, 'min_child_samples': 10, 'subsample': 0.9425354224915806, 'colsample_bytree': 0.7971751941073381, 'reg_alpha': 0.029695396305709505, 'reg_lambda': 0.006323174978013705}. Best is trial 12 with value: 0.9254208333333334.
[I 2025-07-04 04:44:00,503] Trial 13 finished with value: 0.9265354166666666 and parameters: {'learning_rate': 0.0808006893420066, 'num_leaves': 140, 'max_depth': 15, 'min_child_samples': 10, 'subsample': 0.8464204345685973, 'colsample_bytree': 0.6896284271460883, 'reg_alpha': 0.034037411917356535, 'reg_lambda': 0.011542580056519397}. Best is trial 13 with value: 0.9265354166666666.
[I 2025-07-04 04:55:36,240] Trial 14 finished with value: 0.9265416666666667 and parameters: {'learning_rate': 0.08663292380907542, 'num_leaves': 131, 'max_depth': 15, 'min_child_samples': 24, 'subsample': 0.9179136553308997, 'colsample_bytree': 0.7686162509108471, 'reg_alpha': 0.11051553680906451, 'reg_lambda': 0.002490355176930139}. Best is trial 14 with value: 0.9265416666666667.
[I 2025-07-04 05:03:18,929] Trial 15 finished with value: 0.91035625 and parameters: {'learning_rate': 0.09464495282697119, 'num_leaves': 121, 'max_depth': 15, 'min_child_samples': 28, 'subsample': 0.8394481178410811, 'colsample_bytree': 0.6632299446037871, 'reg_alpha': 0.2769471618324971, 'reg_lambda': 0.0020902835877666523}. Best is trial 14 with value: 0.9265416666666667.
[I 2025-07-04 05:12:16,713] Trial 16 finished with value: 0.9075270833333333 and parameters: {'learning_rate': 0.08458021650122764, 'num_leaves': 61, 'max_depth': 14, 'min_child_samples': 23, 'subsample': 0.922208456407407, 'colsample_bytree': 0.7596718889820695, 'reg_alpha': 9.54164792571926, 'reg_lambda': 0.2870960191221483}. Best is trial 14 with value: 0.9265416666666667.
[I 2025-07-04 05:28:13,675] Trial 17 finished with value: 0.93203125 and parameters: {'learning_rate': 0.08421061476917555, 'num_leaves': 195, 'max_depth': 15, 'min_child_samples': 34, 'subsample': 0.8521211323462499, 'colsample_bytree': 0.7458466667011544, 'reg_alpha': 0.049113624259206394, 'reg_lambda': 0.0005495336345457114}. Best is trial 17 with value: 0.93203125.
[I 2025-07-04 05:43:22,822] Trial 18 finished with value: 0.9391895833333334 and parameters: {'learning_rate': 0.09134875615222389, 'num_leaves': 199, 'max_depth': 13, 'min_child_samples': 34, 'subsample': 0.8769232988448797, 'colsample_bytree': 0.7425736208006023, 'reg_alpha': 0.25572452150806746, 'reg_lambda': 0.0006117169730699716}. Best is trial 18 with value: 0.9391895833333334.
[I 2025-07-04 05:54:33,734] Trial 19 finished with value: 0.9215729166666666 and parameters: {'learning_rate': 0.0927905861806416, 'num_leaves': 201, 'max_depth': 13, 'min_child_samples': 40, 'subsample': 0.8745099650772767, 'colsample_bytree': 0.8536846599021631, 'reg_alpha': 0.0004838985819749028, 'reg_lambda': 2.577494632751774e-06}. Best is trial 18 with value: 0.9391895833333334.
[I 2025-07-04 06:02:50,494] Trial 20 finished with value: 0.90905 and parameters: {'learning_rate': 0.04976936504577328, 'num_leaves': 251, 'max_depth': 12, 'min_child_samples': 69, 'subsample': 0.7981797428317376, 'colsample_bytree': 0.7436305420202728, 'reg_alpha': 1.1289547451889395, 'reg_lambda': 0.0002556235435636459}. Best is trial 18 with value: 0.9391895833333334.
[I 2025-07-04 06:17:37,302] Trial 21 finished with value: 0.9368770833333333 and parameters: {'learning_rate': 0.08988492062812059, 'num_leaves': 191, 'max_depth': 14, 'min_child_samples': 32, 'subsample': 0.8974051704963875, 'colsample_bytree': 0.7633265984112636, 'reg_alpha': 0.1492303161120336, 'reg_lambda': 0.0008415327432735549}. Best is trial 18 with value: 0.9391895833333334.
[I 2025-07-04 06:23:34,652] Trial 22 finished with value: 0.91184375 and parameters: {'learning_rate': 0.09938078601047523, 'num_leaves': 198, 'max_depth': 14, 'min_child_samples': 33, 'subsample': 0.8769314930622781, 'colsample_bytree': 0.7410017980120315, 'reg_alpha': 0.11432458098991852, 'reg_lambda': 5.295092277249686e-05}. Best is trial 18 with value: 0.9391895833333334.
[I 2025-07-04 06:37:04,766] Trial 23 finished with value: 0.9333208333333334 and parameters: {'learning_rate': 0.07582315130415085, 'num_leaves': 186, 'max_depth': 14, 'min_child_samples': 47, 'subsample': 0.8331301806943068, 'colsample_bytree': 0.8298518569194255, 'reg_alpha': 1.4727671068824948, 'reg_lambda': 0.0007436803811567548}. Best is trial 18 with value: 0.9391895833333334.
[I 2025-07-04 06:52:24,949] Trial 24 finished with value: 0.93693125 and parameters: {'learning_rate': 0.07676881677519456, 'num_leaves': 222, 'max_depth': 12, 'min_child_samples': 46, 'subsample': 0.8063410724165341, 'colsample_bytree': 0.8343225658849546, 'reg_alpha': 2.3101188307329408, 'reg_lambda': 3.174732927110957e-06}. Best is trial 18 with value: 0.9391895833333334.
[I 2025-07-04 07:07:51,208] Trial 25 finished with value: 0.936425 and parameters: {'learning_rate': 0.09209740735677958, 'num_leaves': 218, 'max_depth': 11, 'min_child_samples': 43, 'subsample': 0.7450821035994762, 'colsample_bytree': 0.8330572005623622, 'reg_alpha': 8.013327786088228, 'reg_lambda': 6.143928864753635e-07}. Best is trial 18 with value: 0.9391895833333334.
[I 2025-07-04 07:26:20,596] Trial 26 finished with value: 0.9349854166666667 and parameters: {'learning_rate': 0.06659061651041212, 'num_leaves': 248, 'max_depth': 12, 'min_child_samples': 64, 'subsample': 0.9494456913715166, 'colsample_bytree': 0.9230585682871244, 'reg_alpha': 0.0012399559792332958, 'reg_lambda': 7.504947547074532e-06}. Best is trial 18 with value: 0.9391895833333334.
[I 2025-07-04 07:42:42,320] Trial 27 finished with value: 0.9212645833333334 and parameters: {'learning_rate': 0.07660408925879786, 'num_leaves': 157, 'max_depth': 8, 'min_child_samples': 50, 'subsample': 0.8091453988885431, 'colsample_bytree': 0.641841993622039, 'reg_alpha': 0.4157082338728052, 'reg_lambda': 6.345498159945885e-07}. Best is trial 18 with value: 0.9391895833333334.
[I 2025-07-04 07:51:33,439] Trial 28 finished with value: 0.9219875 and parameters: {'learning_rate': 0.09228897673109171, 'num_leaves': 222, 'max_depth': 11, 'min_child_samples': 19, 'subsample': 0.6979339536681747, 'colsample_bytree': 0.7804840103847693, 'reg_alpha': 0.015676896772533942, 'reg_lambda': 7.361500547742378e-05}. Best is trial 18 with value: 0.9391895833333334.
[I 2025-07-04 08:05:17,351] Trial 29 finished with value: 0.9331979166666666 and parameters: {'learning_rate': 0.08084209470317968, 'num_leaves': 176, 'max_depth': 13, 'min_child_samples': 57, 'subsample': 0.8977953524733976, 'colsample_bytree': 0.8187674227184883, 'reg_alpha': 2.145755161887688, 'reg_lambda': 6.277118711869998e-06}. Best is trial 18 with value: 0.9391895833333334.

Best trial:
 Value:  0.9391895833333334
 Params:
    learning_rate: 0.09134875615222389
    num_leaves: 199
    max_depth: 13
    min_child_samples: 34
    subsample: 0.8769232988448797
    colsample_bytree: 0.7425736208006023
    reg_alpha: 0.25572452150806746
    reg_lambda: 0.0006117169730699716

In [ ]:
# 최적 파라미터로 전체 학습
best_params = study.best_params

final_model = lgb.LGBMClassifier(**best_params)
# X_tr, X_val, y_tr, y_val
final_model.fit( X_tr, y_tr)

LGBMClassifier(colsample_bytree=0.7425736208006023,
               learning_rate=0.09134875615222389, max_depth=13,
               min_child_samples=34, num_leaves=199,
               reg_alpha=0.25572452150806746, reg_lambda=0.0006117169730699716,
               subsample=0.8769232988448797)

In [ ]:
X_test = test.drop(columns=['기준년월','ID'])

In [ ]:
## 예측
# 5. 예측 수행
final_pred = final_model.predict(X_test)               # 예측 레이블
final_proba = final_model.predict_proba(X_test)

In [ ]:
# 6. 결과 저장
res_df = pd.DataFrame({
    'ID': test.ID,
    'Segment': final_pred
})

In [ ]:
res_df.to_csv('/content/drive/MyDrive/Colab_Notebooks/01.like_lion_final_prj/hyper_pred_result.csv')

In [ ]:
res_df.groupby('ID')['Segment']
    .agg(lambda x: x.mode())

IndentationError: unexpected indent (ipython-input-45-2163916041.py, line 2)

In [ ]:
representative_segments = (
    res_df.groupby('ID')['Segment']
    .agg(lambda x: x.mode().iloc[0])  # mode()는 여러 개일 수 있어 .iloc[0]으로 하나 선택
    .reset_index()
    .rename(columns={'Segment': 'Segment'})
)

print(representative_segments)

               ID Segment
0      TEST_00000       E
1      TEST_00001       D
2      TEST_00002       D
3      TEST_00003       E
4      TEST_00004       E
...           ...     ...
99995  TEST_99995       E
99996  TEST_99996       E
99997  TEST_99997       E
99998  TEST_99998       C
99999  TEST_99999       E

[100000 rows x 2 columns]

In [ ]:
representative_segments.to_csv('/content/drive/MyDrive/Colab_Notebooks/01.like_lion_final_prj/submission_1.csv', index=False)



*   항목 추가
*   항목 추가

In [ ]:
res_df.Segment.value_counts()

Segment
E    495356
D     77128
C     25974
B       806
A       736
Name: count, dtype: int64

In [ ]:
res_df[res_df.Segment == 'A']

                ID Segment
631     TEST_00631       A
1194    TEST_01194       A
2166    TEST_02166       A
2254    TEST_02254       A
3387    TEST_03387       A
...            ...     ...
596571  TEST_96571       A
596614  TEST_96614       A
597520  TEST_97520       A
599537  TEST_99537       A
599734  TEST_99734       A

[736 rows x 2 columns]