In [1]:
import pandas as pd
import os
from glob import glob
import numpy as np
from pandas.api.types import CategoricalDtype

In [2]:
ex1 = pd.read_parquet('train/3.승인매출정보/2018_승인매출정보_전체.parquet')

In [3]:
member_df = pd.read_parquet('train/1.회원정보/2018_회원정보_전체.parquet')
member_seg = member_df[['ID', 'Segment']].drop_duplicates(subset='ID')
ex1 = ex1.merge(member_seg, on='ID', how='left')

In [4]:
all_cols = ex1.columns.tolist()
print("전체 컬럼 이름:")
print(all_cols)
str_cols = ex1.select_dtypes(include=['object']).columns.tolist()
print("\n문자형 컬럼 이름:")
print(str_cols)
num_cols = ex1.select_dtypes(include=[np.number]).columns.tolist()
print("\n숫자형 컬럼 이름:")
print(num_cols)

전체 컬럼 이름:
['기준년월', 'ID', '최종이용일자_기본', '최종이용일자_신판', '최종이용일자_CA', '최종이용일자_카드론', '최종이용일자_체크', '최종이용일자_일시불', '최종이용일자_할부', '이용건수_신용_B0M', '이용건수_신판_B0M', '이용건수_일시불_B0M', '이용건수_할부_B0M', '이용건수_할부_유이자_B0M', '이용건수_할부_무이자_B0M', '이용건수_부분무이자_B0M', '이용건수_CA_B0M', '이용건수_체크_B0M', '이용건수_카드론_B0M', '이용금액_일시불_B0M', '이용금액_할부_B0M', '이용금액_할부_유이자_B0M', '이용금액_할부_무이자_B0M', '이용금액_부분무이자_B0M', '이용금액_CA_B0M', '이용금액_체크_B0M', '이용금액_카드론_B0M', '이용후경과월_신용', '이용후경과월_신판', '이용후경과월_일시불', '이용후경과월_할부', '이용후경과월_할부_유이자', '이용후경과월_할부_무이자', '이용후경과월_부분무이자', '이용후경과월_CA', '이용후경과월_체크', '이용후경과월_카드론', '이용건수_신용_R12M', '이용건수_신판_R12M', '이용건수_일시불_R12M', '이용건수_할부_R12M', '이용건수_할부_유이자_R12M', '이용건수_할부_무이자_R12M', '이용건수_부분무이자_R12M', '이용건수_CA_R12M', '이용건수_체크_R12M', '이용건수_카드론_R12M', '이용금액_일시불_R12M', '이용금액_할부_R12M', '이용금액_할부_유이자_R12M', '이용금액_할부_무이자_R12M', '이용금액_부분무이자_R12M', '이용금액_CA_R12M', '이용금액_체크_R12M', '이용금액_카드론_R12M', '최대이용금액_일시불_R12M', '최대이용금액_할부_R12M', '최대이용금액_할부_유이자_R12M', '최대이용금액_할부_무이자_R12M', '최대이용금액_부분무이자_R12M', '최대이용금액_CA_R12M', '최대이용금액_체크_R12M', '최대이용금액_카드론_R12M', '이용개월수_신용_R12M', '이용개월수_신판_R12M', '이용개월수_일시불_R12M', '이용개월수_할부_R12M', '이용개월수_할부_유이자_R12M', '이용개월수_할부_무이자_R12M', '이용개월수_부분무이자_R12M', '이용개월수_CA_R12M', '이용개월수_체크_R12M', '이용개월수_카드론_R12M', '이용건수_신용_R6M', '이용건수_신판_R6M', '이용건수_일시불_R6M', '이용건수_할부_R6M', '이용건수_할부_유이자_R6M', '이용건수_할부_무이자_R6M', '이용건수_부분무이자_R6M', '이용건수_CA_R6M', '이용건수_체크_R6M', '이용건수_카드론_R6M', '이용금액_일시불_R6M', '이용금액_할부_R6M', '이용금액_할부_유이자_R6M', '이용금액_할부_무이자_R6M', '이용금액_부분무이자_R6M', '이용금액_CA_R6M', '이용금액_체크_R6M', '이용금액_카드론_R6M', '이용개월수_신용_R6M', '이용개월수_신판_R6M', '이용개월수_일시불_R6M', '이용개월수_할부_R6M', '이용개월수_할부_유이자_R6M', '이용개월수_할부_무이자_R6M', '이용개월수_부분무이자_R6M', '이용개월수_CA_R6M', '이용개월수_체크_R6M', '이용개월수_카드론_R6M', '이용건수_신용_R3M', '이용건수_신판_R3M', '이용건수_일시불_R3M', '이용건수_할부_R3M', '이용건수_할부_유이자_R3M', '이용건수_할부_무이자_R3M', '이용건수_부분무이자_R3M', '이용건수_CA_R3M', '이용건수_체크_R3M', '이용건수_카드론_R3M', '이용금액_일시불_R3M', '이용금액_할부_R3M', '이용금액_할부_유이자_R3M', '이용금액_할부_무이자_R3M', '이용금액_부분무이자_R3M', '이용금액_CA_R3M', '이용금액_체크_R3M', '이용금액_카드론_R3M', '이용개월수_신용_R3M', '이용개월수_신판_R3M', '이용개월수_일시불_R3M', '이용개월수_할부_R3M', '이용개월수_할부_유이자_R3M', '이용개월수_할부_무이자_R3M', '이용개월수_부분무이자_R3M', '이용개월수_CA_R3M', '이용개월수_체크_R3M', '이용개월수_카드론_R3M', '이용가맹점수', '이용금액_해외', '쇼핑_도소매_이용금액', '쇼핑_백화점_이용금액', '쇼핑_마트_이용금액', '쇼핑_슈퍼마켓_이용금액', '쇼핑_편의점_이용금액', '쇼핑_아울렛_이용금액', '쇼핑_온라인_이용금액', '쇼핑_기타_이용금액', '교통_주유이용금액', '교통_정비이용금액', '교통_통행료이용금액', '교통_버스지하철이용금액', '교통_택시이용금액', '교통_철도버스이용금액', '여유_운동이용금액', '여유_Pet이용금액', '여유_공연이용금액', '여유_공원이용금액', '여유_숙박이용금액', '여유_여행이용금액', '여유_항공이용금액', '여유_기타이용금액', '납부_통신비이용금액', '납부_관리비이용금액', '납부_렌탈료이용금액', '납부_가스전기료이용금액', '납부_보험료이용금액', '납부_유선방송이용금액', '납부_건강연금이용금액', '납부_기타이용금액', '_1순위업종', '_1순위업종_이용금액', '_2순위업종', '_2순위업종_이용금액', '_3순위업종', '_3순위업종_이용금액', '_1순위쇼핑업종', '_1순위쇼핑업종_이용금액', '_2순위쇼핑업종', '_2순위쇼핑업종_이용금액', '_3순위쇼핑업종', '_3순위쇼핑업종_이용금액', '_1순위교통업종', '_1순위교통업종_이용금액', '_2순위교통업종', '_2순위교통업종_이용금액', '_3순위교통업종', '_3순위교통업종_이용금액', '_1순위여유업종', '_1순위여유업종_이용금액', '_2순위여유업종', '_2순위여유업종_이용금액', '_3순위여유업종', '_3순위여유업종_이용금액', '_1순위납부업종', '_1순위납부업종_이용금액', '_2순위납부업종', '_2순위납부업종_이용금액', '_3순위납부업종', '_3순위납부업종_이용금액', '할부건수_3M_R12M', '할부건수_6M_R12M', '할부건수_12M_R12M', '할부건수_14M_R12M', '할부금액_3M_R12M', '할부금액_6M_R12M', '할부금액_12M_R12M', '할부금액_14M_R12M', '할부건수_유이자_3M_R12M', '할부건수_유이자_6M_R12M', '할부건수_유이자_12M_R12M', '할부건수_유이자_14M_R12M', '할부금액_유이자_3M_R12M', '할부금액_유이자_6M_R12M', '할부금액_유이자_12M_R12M', '할부금액_유이자_14M_R12M', '할부건수_무이자_3M_R12M', '할부건수_무이자_6M_R12M', '할부건수_무이자_12M_R12M', '할부건수_무이자_14M_R12M', '할부금액_무이자_3M_R12M', '할부금액_무이자_6M_R12M', '할부금액_무이자_12M_R12M', '할부금액_무이자_14M_R12M', '할부건수_부분_3M_R12M', '할부건수_부분_6M_R12M', '할부건수_부분_12M_R12M', '할부건수_부분_14M_R12M', '할부금액_부분_3M_R12M', '할부금액_부분_6M_R12M', '할부금액_부분_12M_R12M', '할부금액_부분_14M_R12M', 'RP건수_B0M', 'RP금액_B0M', 'RP유형건수_B0M', 'RP건수_통신_B0M', 'RP건수_아파트_B0M', 'RP건수_제휴사서비스직접판매_B0M', 'RP건수_렌탈_B0M', 'RP건수_가스_B0M', 'RP건수_전기_B0M', 'RP건수_보험_B0M', 'RP건수_학습비_B0M', 'RP건수_유선방송_B0M', 'RP건수_건강_B0M', 'RP건수_교통_B0M', 'RP후경과월', 'RP후경과월_통신', 'RP후경과월_아파트', 'RP후경과월_제휴사서비스직접판매', 'RP후경과월_렌탈', 'RP후경과월_가스', 'RP후경과월_전기', 'RP후경과월_보험', 'RP후경과월_학습비', 'RP후경과월_유선방송', 'RP후경과월_건강', 'RP후경과월_교통', '증감_RP건수_전월', '증감_RP유형건수_전월', '증감_RP건수_통신_전월', '증감_RP건수_아파트_전월', '증감_RP건수_제휴사서비스직접판매_전월', '증감_RP건수_렌탈_전월', '증감_RP건수_가스_전월', '증감_RP건수_전기_전월', '증감_RP건수_보험_전월', '증감_RP건수_학습비_전월', '증감_RP건수_유선방송_전월', '증감_RP건수_건강_전월', '증감_RP건수_교통_전월', '최초카드론이용경과월', '최종카드론이용경과월', '카드론이용건수_누적', '카드론이용월수_누적', '카드론이용금액_누적', '최종카드론_금융상환방식코드', '최종카드론_신청경로코드', '최종카드론_대출이율', '최종카드론_대출일자', '최종카드론_대출월수', '최종카드론_거치개월수', '최종카드론_대출금액', '이용개월수_온라인_R6M', '이용개월수_오프라인_R6M', '이용금액_온라인_R6M', '이용금액_오프라인_R6M', '이용건수_온라인_R6M', '이용건수_오프라인_R6M', '이용금액_온라인_R3M', '이용금액_오프라인_R3M', '이용건수_온라인_R3M', '이용건수_오프라인_R3M', '이용금액_온라인_B0M', '이용금액_오프라인_B0M', '이용건수_온라인_B0M', '이용건수_오프라인_B0M', '이용개월수_페이_온라인_R6M', '이용개월수_페이_오프라인_R6M', '이용금액_페이_온라인_R6M', '이용금액_페이_오프라인_R6M', '이용건수_페이_온라인_R6M', '이용건수_페이_오프라인_R6M', '이용금액_페이_온라인_R3M', '이용금액_페이_오프라인_R3M', '이용건수_페이_온라인_R3M', '이용건수_페이_오프라인_R3M', '이용금액_페이_온라인_B0M', '이용금액_페이_오프라인_B0M', '이용건수_페이_온라인_B0M', '이용건수_페이_오프라인_B0M', '이용개월수_간편결제_R6M', '이용개월수_당사페이_R6M', '이용개월수_당사기타_R6M', '이용개월수_A페이_R6M', '이용개월수_B페이_R6M', '이용개월수_C페이_R6M', '이용개월수_D페이_R6M', '이용금액_간편결제_R6M', '이용금액_당사페이_R6M', '이용금액_당사기타_R6M', '이용금액_A페이_R6M', '이용금액_B페이_R6M', '이용금액_C페이_R6M', '이용금액_D페이_R6M', '이용건수_간편결제_R6M', '이용건수_당사페이_R6M', '이용건수_당사기타_R6M', '이용건수_A페이_R6M', '이용건수_B페이_R6M', '이용건수_C페이_R6M', '이용건수_D페이_R6M', '이용금액_간편결제_R3M', '이용금액_당사페이_R3M', '이용금액_당사기타_R3M', '이용금액_A페이_R3M', '이용금액_B페이_R3M', '이용금액_C페이_R3M', '이용금액_D페이_R3M', '이용건수_간편결제_R3M', '이용건수_당사페이_R3M', '이용건수_당사기타_R3M', '이용건수_A페이_R3M', '이용건수_B페이_R3M', '이용건수_C페이_R3M', '이용건수_D페이_R3M', '이용금액_간편결제_B0M', '이용금액_당사페이_B0M', '이용금액_당사기타_B0M', '이용금액_A페이_B0M', '이용금액_B페이_B0M', '이용금액_C페이_B0M', '이용금액_D페이_B0M', '이용건수_간편결제_B0M', '이용건수_당사페이_B0M', '이용건수_당사기타_B0M', '이용건수_A페이_B0M', '이용건수_B페이_B0M', '이용건수_C페이_B0M', '이용건수_D페이_B0M', '이용개월수_선결제_R6M', '이용횟수_선결제_R6M', '이용금액_선결제_R6M', '이용건수_선결제_R6M', '이용횟수_선결제_R3M', '이용금액_선결제_R3M', '이용건수_선결제_R3M', '이용횟수_선결제_B0M', '이용금액_선결제_B0M', '이용건수_선결제_B0M', '이용횟수_연체_R6M', '이용금액_연체_R6M', '이용횟수_연체_R3M', '이용금액_연체_R3M', '이용횟수_연체_B0M', '이용금액_연체_B0M', '이용개월수_전체_R6M', '이용개월수_전체_R3M', '이용개월수_결제일_R6M', '이용개월수_결제일_R3M', '가맹점매출금액_B1M', '가맹점매출금액_B2M', '정상청구원금_B0M', '선입금원금_B0M', '정상입금원금_B0M', '연체입금원금_B0M', '정상청구원금_B2M', '선입금원금_B2M', '정상입금원금_B2M', '연체입금원금_B2M', '정상청구원금_B5M', '선입금원금_B5M', '정상입금원금_B5M', '연체입금원금_B5M', '건수_할부전환_R6M', '건수_할부전환_R3M', '금액_할부전환_R6M', '금액_할부전환_R3M', '연속무실적개월수_기본_24M_카드', '연속유실적개월수_기본_24M_카드', '신청건수_ATM_CA_B0', '신청건수_ATM_CL_B0', '신청건수_ATM_CA_R6M', '신청건수_ATM_CL_R6M', '승인거절건수_B0M', '승인거절건수_한도초과_B0M', '승인거절건수_BL_B0M', '승인거절건수_입력오류_B0M', '승인거절건수_기타_B0M', '승인거절건수_R3M', '승인거절건수_한도초과_R3M', '승인거절건수_BL_R3M', '승인거절건수_입력오류_R3M', '승인거절건수_기타_R3M', '이용금액대', 'Segment']

문자형 컬럼 이름:
['ID', '_1순위업종', '_2순위업종', '_3순위업종', '_1순위쇼핑업종', '_2순위쇼핑업종', '_3순위쇼핑업종', '_1순위교통업종', '_2순위교통업종', '_3순위교통업종', '_1순위여유업종', '_2순위여유업종', '_3순위여유업종', '_1순위납부업종', '_2순위납부업종', '_3순위납부업종', '최종카드론_신청경로코드', '이용금액대', 'Segment']

숫자형 컬럼 이름:
['기준년월', '최종이용일자_기본', '최종이용일자_신판', '최종이용일자_CA', '최종이용일자_카드론', '최종이용일자_체크', '최종이용일자_일시불', '최종이용일자_할부', '이용건수_신용_B0M', '이용건수_신판_B0M', '이용건수_일시불_B0M', '이용건수_할부_B0M', '이용건수_할부_유이자_B0M', '이용건수_할부_무이자_B0M', '이용건수_부분무이자_B0M', '이용건수_CA_B0M', '이용건수_체크_B0M', '이용건수_카드론_B0M', '이용금액_일시불_B0M', '이용금액_할부_B0M', '이용금액_할부_유이자_B0M', '이용금액_할부_무이자_B0M', '이용금액_부분무이자_B0M', '이용금액_CA_B0M', '이용금액_체크_B0M', '이용금액_카드론_B0M', '이용후경과월_신용', '이용후경과월_신판', '이용후경과월_일시불', '이용후경과월_할부', '이용후경과월_할부_유이자', '이용후경과월_할부_무이자', '이용후경과월_부분무이자', '이용후경과월_CA', '이용후경과월_체크', '이용후경과월_카드론', '이용건수_신용_R12M', '이용건수_신판_R12M', '이용건수_일시불_R12M', '이용건수_할부_R12M', '이용건수_할부_유이자_R12M', '이용건수_할부_무이자_R12M', '이용건수_부분무이자_R12M', '이용건수_CA_R12M', '이용건수_체크_R12M', '이용건수_카드론_R12M', '이용금액_일시불_R12M', '이용금액_할부_R12M', '이용금액_할부_유이자_R12M', '이용금액_할부_무이자_R12M', '이용금액_부분무이자_R12M', '이용금액_CA_R12M', '이용금액_체크_R12M', '이용금액_카드론_R12M', '최대이용금액_일시불_R12M', '최대이용금액_할부_R12M', '최대이용금액_할부_유이자_R12M', '최대이용금액_할부_무이자_R12M', '최대이용금액_부분무이자_R12M', '최대이용금액_CA_R12M', '최대이용금액_체크_R12M', '최대이용금액_카드론_R12M', '이용개월수_신용_R12M', '이용개월수_신판_R12M', '이용개월수_일시불_R12M', '이용개월수_할부_R12M', '이용개월수_할부_유이자_R12M', '이용개월수_할부_무이자_R12M', '이용개월수_부분무이자_R12M', '이용개월수_CA_R12M', '이용개월수_체크_R12M', '이용개월수_카드론_R12M', '이용건수_신용_R6M', '이용건수_신판_R6M', '이용건수_일시불_R6M', '이용건수_할부_R6M', '이용건수_할부_유이자_R6M', '이용건수_할부_무이자_R6M', '이용건수_부분무이자_R6M', '이용건수_CA_R6M', '이용건수_체크_R6M', '이용건수_카드론_R6M', '이용금액_일시불_R6M', '이용금액_할부_R6M', '이용금액_할부_유이자_R6M', '이용금액_할부_무이자_R6M', '이용금액_부분무이자_R6M', '이용금액_CA_R6M', '이용금액_체크_R6M', '이용금액_카드론_R6M', '이용개월수_신용_R6M', '이용개월수_신판_R6M', '이용개월수_일시불_R6M', '이용개월수_할부_R6M', '이용개월수_할부_유이자_R6M', '이용개월수_할부_무이자_R6M', '이용개월수_부분무이자_R6M', '이용개월수_CA_R6M', '이용개월수_체크_R6M', '이용개월수_카드론_R6M', '이용건수_신용_R3M', '이용건수_신판_R3M', '이용건수_일시불_R3M', '이용건수_할부_R3M', '이용건수_할부_유이자_R3M', '이용건수_할부_무이자_R3M', '이용건수_부분무이자_R3M', '이용건수_CA_R3M', '이용건수_체크_R3M', '이용건수_카드론_R3M', '이용금액_일시불_R3M', '이용금액_할부_R3M', '이용금액_할부_유이자_R3M', '이용금액_할부_무이자_R3M', '이용금액_부분무이자_R3M', '이용금액_CA_R3M', '이용금액_체크_R3M', '이용금액_카드론_R3M', '이용개월수_신용_R3M', '이용개월수_신판_R3M', '이용개월수_일시불_R3M', '이용개월수_할부_R3M', '이용개월수_할부_유이자_R3M', '이용개월수_할부_무이자_R3M', '이용개월수_부분무이자_R3M', '이용개월수_CA_R3M', '이용개월수_체크_R3M', '이용개월수_카드론_R3M', '이용가맹점수', '이용금액_해외', '쇼핑_도소매_이용금액', '쇼핑_백화점_이용금액', '쇼핑_마트_이용금액', '쇼핑_슈퍼마켓_이용금액', '쇼핑_편의점_이용금액', '쇼핑_아울렛_이용금액', '쇼핑_온라인_이용금액', '쇼핑_기타_이용금액', '교통_주유이용금액', '교통_정비이용금액', '교통_통행료이용금액', '교통_버스지하철이용금액', '교통_택시이용금액', '교통_철도버스이용금액', '여유_운동이용금액', '여유_Pet이용금액', '여유_공연이용금액', '여유_공원이용금액', '여유_숙박이용금액', '여유_여행이용금액', '여유_항공이용금액', '여유_기타이용금액', '납부_통신비이용금액', '납부_관리비이용금액', '납부_렌탈료이용금액', '납부_가스전기료이용금액', '납부_보험료이용금액', '납부_유선방송이용금액', '납부_건강연금이용금액', '납부_기타이용금액', '_1순위업종_이용금액', '_2순위업종_이용금액', '_3순위업종_이용금액', '_1순위쇼핑업종_이용금액', '_2순위쇼핑업종_이용금액', '_3순위쇼핑업종_이용금액', '_1순위교통업종_이용금액', '_2순위교통업종_이용금액', '_3순위교통업종_이용금액', '_1순위여유업종_이용금액', '_2순위여유업종_이용금액', '_3순위여유업종_이용금액', '_1순위납부업종_이용금액', '_2순위납부업종_이용금액', '_3순위납부업종_이용금액', '할부건수_3M_R12M', '할부건수_6M_R12M', '할부건수_12M_R12M', '할부건수_14M_R12M', '할부금액_3M_R12M', '할부금액_6M_R12M', '할부금액_12M_R12M', '할부금액_14M_R12M', '할부건수_유이자_3M_R12M', '할부건수_유이자_6M_R12M', '할부건수_유이자_12M_R12M', '할부건수_유이자_14M_R12M', '할부금액_유이자_3M_R12M', '할부금액_유이자_6M_R12M', '할부금액_유이자_12M_R12M', '할부금액_유이자_14M_R12M', '할부건수_무이자_3M_R12M', '할부건수_무이자_6M_R12M', '할부건수_무이자_12M_R12M', '할부건수_무이자_14M_R12M', '할부금액_무이자_3M_R12M', '할부금액_무이자_6M_R12M', '할부금액_무이자_12M_R12M', '할부금액_무이자_14M_R12M', '할부건수_부분_3M_R12M', '할부건수_부분_6M_R12M', '할부건수_부분_12M_R12M', '할부건수_부분_14M_R12M', '할부금액_부분_3M_R12M', '할부금액_부분_6M_R12M', '할부금액_부분_12M_R12M', '할부금액_부분_14M_R12M', 'RP건수_B0M', 'RP금액_B0M', 'RP유형건수_B0M', 'RP건수_통신_B0M', 'RP건수_아파트_B0M', 'RP건수_제휴사서비스직접판매_B0M', 'RP건수_렌탈_B0M', 'RP건수_가스_B0M', 'RP건수_전기_B0M', 'RP건수_보험_B0M', 'RP건수_학습비_B0M', 'RP건수_유선방송_B0M', 'RP건수_건강_B0M', 'RP건수_교통_B0M', 'RP후경과월', 'RP후경과월_통신', 'RP후경과월_아파트', 'RP후경과월_제휴사서비스직접판매', 'RP후경과월_렌탈', 'RP후경과월_가스', 'RP후경과월_전기', 'RP후경과월_보험', 'RP후경과월_학습비', 'RP후경과월_유선방송', 'RP후경과월_건강', 'RP후경과월_교통', '증감_RP건수_전월', '증감_RP유형건수_전월', '증감_RP건수_통신_전월', '증감_RP건수_아파트_전월', '증감_RP건수_제휴사서비스직접판매_전월', '증감_RP건수_렌탈_전월', '증감_RP건수_가스_전월', '증감_RP건수_전기_전월', '증감_RP건수_보험_전월', '증감_RP건수_학습비_전월', '증감_RP건수_유선방송_전월', '증감_RP건수_건강_전월', '증감_RP건수_교통_전월', '최초카드론이용경과월', '최종카드론이용경과월', '카드론이용건수_누적', '카드론이용월수_누적', '카드론이용금액_누적', '최종카드론_금융상환방식코드', '최종카드론_대출이율', '최종카드론_대출일자', '최종카드론_대출월수', '최종카드론_거치개월수', '최종카드론_대출금액', '이용개월수_온라인_R6M', '이용개월수_오프라인_R6M', '이용금액_온라인_R6M', '이용금액_오프라인_R6M', '이용건수_온라인_R6M', '이용건수_오프라인_R6M', '이용금액_온라인_R3M', '이용금액_오프라인_R3M', '이용건수_온라인_R3M', '이용건수_오프라인_R3M', '이용금액_온라인_B0M', '이용금액_오프라인_B0M', '이용건수_온라인_B0M', '이용건수_오프라인_B0M', '이용개월수_페이_온라인_R6M', '이용개월수_페이_오프라인_R6M', '이용금액_페이_온라인_R6M', '이용금액_페이_오프라인_R6M', '이용건수_페이_온라인_R6M', '이용건수_페이_오프라인_R6M', '이용금액_페이_온라인_R3M', '이용금액_페이_오프라인_R3M', '이용건수_페이_온라인_R3M', '이용건수_페이_오프라인_R3M', '이용금액_페이_온라인_B0M', '이용금액_페이_오프라인_B0M', '이용건수_페이_온라인_B0M', '이용건수_페이_오프라인_B0M', '이용개월수_간편결제_R6M', '이용개월수_당사페이_R6M', '이용개월수_당사기타_R6M', '이용개월수_A페이_R6M', '이용개월수_B페이_R6M', '이용개월수_C페이_R6M', '이용개월수_D페이_R6M', '이용금액_간편결제_R6M', '이용금액_당사페이_R6M', '이용금액_당사기타_R6M', '이용금액_A페이_R6M', '이용금액_B페이_R6M', '이용금액_C페이_R6M', '이용금액_D페이_R6M', '이용건수_간편결제_R6M', '이용건수_당사페이_R6M', '이용건수_당사기타_R6M', '이용건수_A페이_R6M', '이용건수_B페이_R6M', '이용건수_C페이_R6M', '이용건수_D페이_R6M', '이용금액_간편결제_R3M', '이용금액_당사페이_R3M', '이용금액_당사기타_R3M', '이용금액_A페이_R3M', '이용금액_B페이_R3M', '이용금액_C페이_R3M', '이용금액_D페이_R3M', '이용건수_간편결제_R3M', '이용건수_당사페이_R3M', '이용건수_당사기타_R3M', '이용건수_A페이_R3M', '이용건수_B페이_R3M', '이용건수_C페이_R3M', '이용건수_D페이_R3M', '이용금액_간편결제_B0M', '이용금액_당사페이_B0M', '이용금액_당사기타_B0M', '이용금액_A페이_B0M', '이용금액_B페이_B0M', '이용금액_C페이_B0M', '이용금액_D페이_B0M', '이용건수_간편결제_B0M', '이용건수_당사페이_B0M', '이용건수_당사기타_B0M', '이용건수_A페이_B0M', '이용건수_B페이_B0M', '이용건수_C페이_B0M', '이용건수_D페이_B0M', '이용개월수_선결제_R6M', '이용횟수_선결제_R6M', '이용금액_선결제_R6M', '이용건수_선결제_R6M', '이용횟수_선결제_R3M', '이용금액_선결제_R3M', '이용건수_선결제_R3M', '이용횟수_선결제_B0M', '이용금액_선결제_B0M', '이용건수_선결제_B0M', '이용횟수_연체_R6M', '이용금액_연체_R6M', '이용횟수_연체_R3M', '이용금액_연체_R3M', '이용횟수_연체_B0M', '이용금액_연체_B0M', '이용개월수_전체_R6M', '이용개월수_전체_R3M', '이용개월수_결제일_R6M', '이용개월수_결제일_R3M', '가맹점매출금액_B1M', '가맹점매출금액_B2M', '정상청구원금_B0M', '선입금원금_B0M', '정상입금원금_B0M', '연체입금원금_B0M', '정상청구원금_B2M', '선입금원금_B2M', '정상입금원금_B2M', '연체입금원금_B2M', '정상청구원금_B5M', '선입금원금_B5M', '정상입금원금_B5M', '연체입금원금_B5M', '건수_할부전환_R6M', '건수_할부전환_R3M', '금액_할부전환_R6M', '금액_할부전환_R3M', '연속무실적개월수_기본_24M_카드', '연속유실적개월수_기본_24M_카드', '신청건수_ATM_CA_B0', '신청건수_ATM_CL_B0', '신청건수_ATM_CA_R6M', '신청건수_ATM_CL_R6M', '승인거절건수_B0M', '승인거절건수_한도초과_B0M', '승인거절건수_BL_B0M', '승인거절건수_입력오류_B0M', '승인거절건수_기타_B0M', '승인거절건수_R3M', '승인거절건수_한도초과_R3M', '승인거절건수_BL_R3M', '승인거절건수_입력오류_R3M', '승인거절건수_기타_R3M']

In [5]:
cols = ['_1순위업종', '_2순위업종', '_3순위업종', '_1순위쇼핑업종', '_2순위쇼핑업종', '_3순위쇼핑업종', '_1순위교통업종', '_2순위교통업종', '_3순위교통업종', '_1순위여유업종', '_2순위여유업종', '_3순위여유업종', '_1순위납부업종', '_2순위납부업종', '_3순위납부업종', '최종카드론_신청경로코드', '이용금액대']
print(ex1[cols].head())

  _1순위업종 _2순위업종 _3순위업종 _1순위쇼핑업종 _2순위쇼핑업종 _3순위쇼핑업종 _1순위교통업종 _2순위교통업종 _3순위교통업종  \
0     납부     쇼핑   사교활동     쇼핑기타     None     None       택시    버스지하철     None
1     쇼핑     납부     교통      도소매     슈퍼마켓      편의점       주유     철도버스     None
2     쇼핑   사교활동     교통      온라인      도소매       마트       주유     None     None
3     쇼핑     납부   사교활동       마트     슈퍼마켓     None       택시     None     None
4   None   None   None     None     None     None     None     None     None

  _1순위여유업종 _2순위여유업종 _3순위여유업종 _1순위납부업종 _2순위납부업종 _3순위납부업종 최종카드론_신청경로코드  \
0     None     None     None      보험료     납부기타     None         None
1     None     None     None      통신비     None     None            8
2     None     None     None     None     None     None            8
3     None     None     None      보험료     None     None         None
4     None     None     None     None     None     None         None

       이용금액대
0  01.100만원+
1   03.30만원+
2  01.100만원+
3  01.100만원+
4     09.미사용

In [6]:
cols = [
    '_1순위업종', '_2순위업종', '_3순위업종',
    '_1순위쇼핑업종', '_2순위쇼핑업종', '_3순위쇼핑업종',
    '_1순위교통업종', '_2순위교통업종', '_3순위교통업종',
    '_1순위여유업종', '_2순위여유업종', '_3순위여유업종',
    '_1순위납부업종', '_2순위납부업종', '_3순위납부업종',
    '최종카드론_신청경로코드', '이용금액대'
]

for col in cols:
    if col in ex1.columns:
        print(f"[{col}] unique values:")
        print(ex1[col].unique())
        print()
    else:
        print(f"[{col}] is not in the DataFrame.\n")

[_1순위업종] unique values:
['납부' '쇼핑' None '사교활동' '교육' '교통' '해외' '의료' '여유생활' '일상생활' '요식']

[_2순위업종] unique values:
['쇼핑' '납부' '사교활동' None '교통' '해외' '의료' '교육' '여유생활' '일상생활' '요식']

[_3순위업종] unique values:
['사교활동' '교통' None '납부' '쇼핑' '여유생활' '의료' '해외' '일상생활' '교육' '요식']

[_1순위쇼핑업종] unique values:
['쇼핑기타' '도소매' '온라인' '마트' None '슈퍼마켓' '편의점' '백화점' '아울렛']

[_2순위쇼핑업종] unique values:
[None '슈퍼마켓' '도소매' '편의점' '마트' '쇼핑기타' '온라인' '아울렛' '백화점']

[_3순위쇼핑업종] unique values:
[None '편의점' '마트' '슈퍼마켓' '도소매' '쇼핑기타' '백화점' '아울렛' '온라인']

[_1순위교통업종] unique values:
['택시' '주유' None '버스지하철' '정비' '철도버스']

[_2순위교통업종] unique values:
['버스지하철' '철도버스' None '정비' '택시' '주유' '통행료']

[_3순위교통업종] unique values:
[None '택시' '철도버스' '정비' '버스지하철' '통행료']

[_1순위여유업종] unique values:
[None '공연' '여유기타' '운동' 'Pet' '항공' '숙박' '공원']

[_2순위여유업종] unique values:
[None '여유기타' '공연' '숙박' 'Pet' '운동' '공원' '항공']

[_3순위여유업종] unique values:
[None '공연' 'Pet' '여유기타' '숙박' '공원' '운동']

[_1순위납부업종] unique values:
['보험료' '통신비' None '관리비' '납부기타' '가스/전기료']

[_2순위납부업종] unique values:
['납부기타' None '통신비' '가스/전기료' '보험료' '관리비']

[_3순위납부업종] unique values:
[None '납부기타' '보험료' '통신비' '가스/전기료']

[최종카드론_신청경로코드] unique values:
[None '8' '1' '7' 'D' '2']

[이용금액대] unique values:
['01.100만원+' '03.30만원+' '09.미사용' '04.10만원+' '02.50만원+' '05.10만원-']

In [7]:
ex1 = ex1.fillna(-1)
cols = [
    '_1순위업종', '_2순위업종', '_3순위업종',
    '_1순위쇼핑업종', '_2순위쇼핑업종', '_3순위쇼핑업종',
    '_1순위교통업종', '_2순위교통업종', '_3순위교통업종',
    '_1순위여유업종', '_2순위여유업종', '_3순위여유업종',
    '_1순위납부업종', '_2순위납부업종', '_3순위납부업종',
    '최종카드론_신청경로코드', '이용금액대'
]

for col in cols:
    if col in ex1.columns:
        print(f"[{col}] unique values:")
        print(ex1[col].unique())
        print()
    else:
        print(f"[{col}] is not in the DataFrame.\n")

[_1순위업종] unique values:
['납부' '쇼핑' -1 '사교활동' '교육' '교통' '해외' '의료' '여유생활' '일상생활' '요식']

[_2순위업종] unique values:
['쇼핑' '납부' '사교활동' -1 '교통' '해외' '의료' '교육' '여유생활' '일상생활' '요식']

[_3순위업종] unique values:
['사교활동' '교통' -1 '납부' '쇼핑' '여유생활' '의료' '해외' '일상생활' '교육' '요식']

[_1순위쇼핑업종] unique values:
['쇼핑기타' '도소매' '온라인' '마트' -1 '슈퍼마켓' '편의점' '백화점' '아울렛']

[_2순위쇼핑업종] unique values:
[-1 '슈퍼마켓' '도소매' '편의점' '마트' '쇼핑기타' '온라인' '아울렛' '백화점']

[_3순위쇼핑업종] unique values:
[-1 '편의점' '마트' '슈퍼마켓' '도소매' '쇼핑기타' '백화점' '아울렛' '온라인']

[_1순위교통업종] unique values:
['택시' '주유' -1 '버스지하철' '정비' '철도버스']

[_2순위교통업종] unique values:
['버스지하철' '철도버스' -1 '정비' '택시' '주유' '통행료']

[_3순위교통업종] unique values:
[-1 '택시' '철도버스' '정비' '버스지하철' '통행료']

[_1순위여유업종] unique values:
[-1 '공연' '여유기타' '운동' 'Pet' '항공' '숙박' '공원']

[_2순위여유업종] unique values:
[-1 '여유기타' '공연' '숙박' 'Pet' '운동' '공원' '항공']

[_3순위여유업종] unique values:
[-1 '공연' 'Pet' '여유기타' '숙박' '공원' '운동']

[_1순위납부업종] unique values:
['보험료' '통신비' -1 '관리비' '납부기타' '가스/전기료']

[_2순위납부업종] unique values:
['납부기타' -1 '통신비' '가스/전기료' '보험료' '관리비']

[_3순위납부업종] unique values:
[-1 '납부기타' '보험료' '통신비' '가스/전기료']

[최종카드론_신청경로코드] unique values:
[-1 '8' '1' '7' 'D' '2']

[이용금액대] unique values:
['01.100만원+' '03.30만원+' '09.미사용' '04.10만원+' '02.50만원+' '05.10만원-']

In [8]:
le_cols = [
    '_1순위업종', '_2순위업종', '_3순위업종',
    '_1순위쇼핑업종', '_2순위쇼핑업종', '_3순위쇼핑업종',
    '_1순위교통업종', '_2순위교통업종', '_3순위교통업종',
    '_1순위여유업종', '_2순위여유업종', '_3순위여유업종',
    '_1순위납부업종', '_2순위납부업종', '_3순위납부업종',
    '최종카드론_신청경로코드', '이용금액대'
]

for col in le_cols:
    ex1[col] = ex1[col].fillna(-1)  # NaN → -1
    codes, uniques = pd.factorize(ex1[col], sort=True)
    ex1[col] = codes

In [9]:
all_cols = ex1.columns.tolist()
print("전체 컬럼 이름:")
print(all_cols)
str_cols = ex1.select_dtypes(include=['object']).columns.tolist()
print("\n문자형 컬럼 이름:")
print(str_cols)
num_cols = ex1.select_dtypes(include=[np.number]).columns.tolist()
print("\n숫자형 컬럼 이름:")
print(num_cols)

전체 컬럼 이름:
['기준년월', 'ID', '최종이용일자_기본', '최종이용일자_신판', '최종이용일자_CA', '최종이용일자_카드론', '최종이용일자_체크', '최종이용일자_일시불', '최종이용일자_할부', '이용건수_신용_B0M', '이용건수_신판_B0M', '이용건수_일시불_B0M', '이용건수_할부_B0M', '이용건수_할부_유이자_B0M', '이용건수_할부_무이자_B0M', '이용건수_부분무이자_B0M', '이용건수_CA_B0M', '이용건수_체크_B0M', '이용건수_카드론_B0M', '이용금액_일시불_B0M', '이용금액_할부_B0M', '이용금액_할부_유이자_B0M', '이용금액_할부_무이자_B0M', '이용금액_부분무이자_B0M', '이용금액_CA_B0M', '이용금액_체크_B0M', '이용금액_카드론_B0M', '이용후경과월_신용', '이용후경과월_신판', '이용후경과월_일시불', '이용후경과월_할부', '이용후경과월_할부_유이자', '이용후경과월_할부_무이자', '이용후경과월_부분무이자', '이용후경과월_CA', '이용후경과월_체크', '이용후경과월_카드론', '이용건수_신용_R12M', '이용건수_신판_R12M', '이용건수_일시불_R12M', '이용건수_할부_R12M', '이용건수_할부_유이자_R12M', '이용건수_할부_무이자_R12M', '이용건수_부분무이자_R12M', '이용건수_CA_R12M', '이용건수_체크_R12M', '이용건수_카드론_R12M', '이용금액_일시불_R12M', '이용금액_할부_R12M', '이용금액_할부_유이자_R12M', '이용금액_할부_무이자_R12M', '이용금액_부분무이자_R12M', '이용금액_CA_R12M', '이용금액_체크_R12M', '이용금액_카드론_R12M', '최대이용금액_일시불_R12M', '최대이용금액_할부_R12M', '최대이용금액_할부_유이자_R12M', '최대이용금액_할부_무이자_R12M', '최대이용금액_부분무이자_R12M', '최대이용금액_CA_R12M', '최대이용금액_체크_R12M', '최대이용금액_카드론_R12M', '이용개월수_신용_R12M', '이용개월수_신판_R12M', '이용개월수_일시불_R12M', '이용개월수_할부_R12M', '이용개월수_할부_유이자_R12M', '이용개월수_할부_무이자_R12M', '이용개월수_부분무이자_R12M', '이용개월수_CA_R12M', '이용개월수_체크_R12M', '이용개월수_카드론_R12M', '이용건수_신용_R6M', '이용건수_신판_R6M', '이용건수_일시불_R6M', '이용건수_할부_R6M', '이용건수_할부_유이자_R6M', '이용건수_할부_무이자_R6M', '이용건수_부분무이자_R6M', '이용건수_CA_R6M', '이용건수_체크_R6M', '이용건수_카드론_R6M', '이용금액_일시불_R6M', '이용금액_할부_R6M', '이용금액_할부_유이자_R6M', '이용금액_할부_무이자_R6M', '이용금액_부분무이자_R6M', '이용금액_CA_R6M', '이용금액_체크_R6M', '이용금액_카드론_R6M', '이용개월수_신용_R6M', '이용개월수_신판_R6M', '이용개월수_일시불_R6M', '이용개월수_할부_R6M', '이용개월수_할부_유이자_R6M', '이용개월수_할부_무이자_R6M', '이용개월수_부분무이자_R6M', '이용개월수_CA_R6M', '이용개월수_체크_R6M', '이용개월수_카드론_R6M', '이용건수_신용_R3M', '이용건수_신판_R3M', '이용건수_일시불_R3M', '이용건수_할부_R3M', '이용건수_할부_유이자_R3M', '이용건수_할부_무이자_R3M', '이용건수_부분무이자_R3M', '이용건수_CA_R3M', '이용건수_체크_R3M', '이용건수_카드론_R3M', '이용금액_일시불_R3M', '이용금액_할부_R3M', '이용금액_할부_유이자_R3M', '이용금액_할부_무이자_R3M', '이용금액_부분무이자_R3M', '이용금액_CA_R3M', '이용금액_체크_R3M', '이용금액_카드론_R3M', '이용개월수_신용_R3M', '이용개월수_신판_R3M', '이용개월수_일시불_R3M', '이용개월수_할부_R3M', '이용개월수_할부_유이자_R3M', '이용개월수_할부_무이자_R3M', '이용개월수_부분무이자_R3M', '이용개월수_CA_R3M', '이용개월수_체크_R3M', '이용개월수_카드론_R3M', '이용가맹점수', '이용금액_해외', '쇼핑_도소매_이용금액', '쇼핑_백화점_이용금액', '쇼핑_마트_이용금액', '쇼핑_슈퍼마켓_이용금액', '쇼핑_편의점_이용금액', '쇼핑_아울렛_이용금액', '쇼핑_온라인_이용금액', '쇼핑_기타_이용금액', '교통_주유이용금액', '교통_정비이용금액', '교통_통행료이용금액', '교통_버스지하철이용금액', '교통_택시이용금액', '교통_철도버스이용금액', '여유_운동이용금액', '여유_Pet이용금액', '여유_공연이용금액', '여유_공원이용금액', '여유_숙박이용금액', '여유_여행이용금액', '여유_항공이용금액', '여유_기타이용금액', '납부_통신비이용금액', '납부_관리비이용금액', '납부_렌탈료이용금액', '납부_가스전기료이용금액', '납부_보험료이용금액', '납부_유선방송이용금액', '납부_건강연금이용금액', '납부_기타이용금액', '_1순위업종', '_1순위업종_이용금액', '_2순위업종', '_2순위업종_이용금액', '_3순위업종', '_3순위업종_이용금액', '_1순위쇼핑업종', '_1순위쇼핑업종_이용금액', '_2순위쇼핑업종', '_2순위쇼핑업종_이용금액', '_3순위쇼핑업종', '_3순위쇼핑업종_이용금액', '_1순위교통업종', '_1순위교통업종_이용금액', '_2순위교통업종', '_2순위교통업종_이용금액', '_3순위교통업종', '_3순위교통업종_이용금액', '_1순위여유업종', '_1순위여유업종_이용금액', '_2순위여유업종', '_2순위여유업종_이용금액', '_3순위여유업종', '_3순위여유업종_이용금액', '_1순위납부업종', '_1순위납부업종_이용금액', '_2순위납부업종', '_2순위납부업종_이용금액', '_3순위납부업종', '_3순위납부업종_이용금액', '할부건수_3M_R12M', '할부건수_6M_R12M', '할부건수_12M_R12M', '할부건수_14M_R12M', '할부금액_3M_R12M', '할부금액_6M_R12M', '할부금액_12M_R12M', '할부금액_14M_R12M', '할부건수_유이자_3M_R12M', '할부건수_유이자_6M_R12M', '할부건수_유이자_12M_R12M', '할부건수_유이자_14M_R12M', '할부금액_유이자_3M_R12M', '할부금액_유이자_6M_R12M', '할부금액_유이자_12M_R12M', '할부금액_유이자_14M_R12M', '할부건수_무이자_3M_R12M', '할부건수_무이자_6M_R12M', '할부건수_무이자_12M_R12M', '할부건수_무이자_14M_R12M', '할부금액_무이자_3M_R12M', '할부금액_무이자_6M_R12M', '할부금액_무이자_12M_R12M', '할부금액_무이자_14M_R12M', '할부건수_부분_3M_R12M', '할부건수_부분_6M_R12M', '할부건수_부분_12M_R12M', '할부건수_부분_14M_R12M', '할부금액_부분_3M_R12M', '할부금액_부분_6M_R12M', '할부금액_부분_12M_R12M', '할부금액_부분_14M_R12M', 'RP건수_B0M', 'RP금액_B0M', 'RP유형건수_B0M', 'RP건수_통신_B0M', 'RP건수_아파트_B0M', 'RP건수_제휴사서비스직접판매_B0M', 'RP건수_렌탈_B0M', 'RP건수_가스_B0M', 'RP건수_전기_B0M', 'RP건수_보험_B0M', 'RP건수_학습비_B0M', 'RP건수_유선방송_B0M', 'RP건수_건강_B0M', 'RP건수_교통_B0M', 'RP후경과월', 'RP후경과월_통신', 'RP후경과월_아파트', 'RP후경과월_제휴사서비스직접판매', 'RP후경과월_렌탈', 'RP후경과월_가스', 'RP후경과월_전기', 'RP후경과월_보험', 'RP후경과월_학습비', 'RP후경과월_유선방송', 'RP후경과월_건강', 'RP후경과월_교통', '증감_RP건수_전월', '증감_RP유형건수_전월', '증감_RP건수_통신_전월', '증감_RP건수_아파트_전월', '증감_RP건수_제휴사서비스직접판매_전월', '증감_RP건수_렌탈_전월', '증감_RP건수_가스_전월', '증감_RP건수_전기_전월', '증감_RP건수_보험_전월', '증감_RP건수_학습비_전월', '증감_RP건수_유선방송_전월', '증감_RP건수_건강_전월', '증감_RP건수_교통_전월', '최초카드론이용경과월', '최종카드론이용경과월', '카드론이용건수_누적', '카드론이용월수_누적', '카드론이용금액_누적', '최종카드론_금융상환방식코드', '최종카드론_신청경로코드', '최종카드론_대출이율', '최종카드론_대출일자', '최종카드론_대출월수', '최종카드론_거치개월수', '최종카드론_대출금액', '이용개월수_온라인_R6M', '이용개월수_오프라인_R6M', '이용금액_온라인_R6M', '이용금액_오프라인_R6M', '이용건수_온라인_R6M', '이용건수_오프라인_R6M', '이용금액_온라인_R3M', '이용금액_오프라인_R3M', '이용건수_온라인_R3M', '이용건수_오프라인_R3M', '이용금액_온라인_B0M', '이용금액_오프라인_B0M', '이용건수_온라인_B0M', '이용건수_오프라인_B0M', '이용개월수_페이_온라인_R6M', '이용개월수_페이_오프라인_R6M', '이용금액_페이_온라인_R6M', '이용금액_페이_오프라인_R6M', '이용건수_페이_온라인_R6M', '이용건수_페이_오프라인_R6M', '이용금액_페이_온라인_R3M', '이용금액_페이_오프라인_R3M', '이용건수_페이_온라인_R3M', '이용건수_페이_오프라인_R3M', '이용금액_페이_온라인_B0M', '이용금액_페이_오프라인_B0M', '이용건수_페이_온라인_B0M', '이용건수_페이_오프라인_B0M', '이용개월수_간편결제_R6M', '이용개월수_당사페이_R6M', '이용개월수_당사기타_R6M', '이용개월수_A페이_R6M', '이용개월수_B페이_R6M', '이용개월수_C페이_R6M', '이용개월수_D페이_R6M', '이용금액_간편결제_R6M', '이용금액_당사페이_R6M', '이용금액_당사기타_R6M', '이용금액_A페이_R6M', '이용금액_B페이_R6M', '이용금액_C페이_R6M', '이용금액_D페이_R6M', '이용건수_간편결제_R6M', '이용건수_당사페이_R6M', '이용건수_당사기타_R6M', '이용건수_A페이_R6M', '이용건수_B페이_R6M', '이용건수_C페이_R6M', '이용건수_D페이_R6M', '이용금액_간편결제_R3M', '이용금액_당사페이_R3M', '이용금액_당사기타_R3M', '이용금액_A페이_R3M', '이용금액_B페이_R3M', '이용금액_C페이_R3M', '이용금액_D페이_R3M', '이용건수_간편결제_R3M', '이용건수_당사페이_R3M', '이용건수_당사기타_R3M', '이용건수_A페이_R3M', '이용건수_B페이_R3M', '이용건수_C페이_R3M', '이용건수_D페이_R3M', '이용금액_간편결제_B0M', '이용금액_당사페이_B0M', '이용금액_당사기타_B0M', '이용금액_A페이_B0M', '이용금액_B페이_B0M', '이용금액_C페이_B0M', '이용금액_D페이_B0M', '이용건수_간편결제_B0M', '이용건수_당사페이_B0M', '이용건수_당사기타_B0M', '이용건수_A페이_B0M', '이용건수_B페이_B0M', '이용건수_C페이_B0M', '이용건수_D페이_B0M', '이용개월수_선결제_R6M', '이용횟수_선결제_R6M', '이용금액_선결제_R6M', '이용건수_선결제_R6M', '이용횟수_선결제_R3M', '이용금액_선결제_R3M', '이용건수_선결제_R3M', '이용횟수_선결제_B0M', '이용금액_선결제_B0M', '이용건수_선결제_B0M', '이용횟수_연체_R6M', '이용금액_연체_R6M', '이용횟수_연체_R3M', '이용금액_연체_R3M', '이용횟수_연체_B0M', '이용금액_연체_B0M', '이용개월수_전체_R6M', '이용개월수_전체_R3M', '이용개월수_결제일_R6M', '이용개월수_결제일_R3M', '가맹점매출금액_B1M', '가맹점매출금액_B2M', '정상청구원금_B0M', '선입금원금_B0M', '정상입금원금_B0M', '연체입금원금_B0M', '정상청구원금_B2M', '선입금원금_B2M', '정상입금원금_B2M', '연체입금원금_B2M', '정상청구원금_B5M', '선입금원금_B5M', '정상입금원금_B5M', '연체입금원금_B5M', '건수_할부전환_R6M', '건수_할부전환_R3M', '금액_할부전환_R6M', '금액_할부전환_R3M', '연속무실적개월수_기본_24M_카드', '연속유실적개월수_기본_24M_카드', '신청건수_ATM_CA_B0', '신청건수_ATM_CL_B0', '신청건수_ATM_CA_R6M', '신청건수_ATM_CL_R6M', '승인거절건수_B0M', '승인거절건수_한도초과_B0M', '승인거절건수_BL_B0M', '승인거절건수_입력오류_B0M', '승인거절건수_기타_B0M', '승인거절건수_R3M', '승인거절건수_한도초과_R3M', '승인거절건수_BL_R3M', '승인거절건수_입력오류_R3M', '승인거절건수_기타_R3M', '이용금액대', 'Segment']

문자형 컬럼 이름:
['ID', 'Segment']

숫자형 컬럼 이름:
['기준년월', '최종이용일자_기본', '최종이용일자_신판', '최종이용일자_CA', '최종이용일자_카드론', '최종이용일자_체크', '최종이용일자_일시불', '최종이용일자_할부', '이용건수_신용_B0M', '이용건수_신판_B0M', '이용건수_일시불_B0M', '이용건수_할부_B0M', '이용건수_할부_유이자_B0M', '이용건수_할부_무이자_B0M', '이용건수_부분무이자_B0M', '이용건수_CA_B0M', '이용건수_체크_B0M', '이용건수_카드론_B0M', '이용금액_일시불_B0M', '이용금액_할부_B0M', '이용금액_할부_유이자_B0M', '이용금액_할부_무이자_B0M', '이용금액_부분무이자_B0M', '이용금액_CA_B0M', '이용금액_체크_B0M', '이용금액_카드론_B0M', '이용후경과월_신용', '이용후경과월_신판', '이용후경과월_일시불', '이용후경과월_할부', '이용후경과월_할부_유이자', '이용후경과월_할부_무이자', '이용후경과월_부분무이자', '이용후경과월_CA', '이용후경과월_체크', '이용후경과월_카드론', '이용건수_신용_R12M', '이용건수_신판_R12M', '이용건수_일시불_R12M', '이용건수_할부_R12M', '이용건수_할부_유이자_R12M', '이용건수_할부_무이자_R12M', '이용건수_부분무이자_R12M', '이용건수_CA_R12M', '이용건수_체크_R12M', '이용건수_카드론_R12M', '이용금액_일시불_R12M', '이용금액_할부_R12M', '이용금액_할부_유이자_R12M', '이용금액_할부_무이자_R12M', '이용금액_부분무이자_R12M', '이용금액_CA_R12M', '이용금액_체크_R12M', '이용금액_카드론_R12M', '최대이용금액_일시불_R12M', '최대이용금액_할부_R12M', '최대이용금액_할부_유이자_R12M', '최대이용금액_할부_무이자_R12M', '최대이용금액_부분무이자_R12M', '최대이용금액_CA_R12M', '최대이용금액_체크_R12M', '최대이용금액_카드론_R12M', '이용개월수_신용_R12M', '이용개월수_신판_R12M', '이용개월수_일시불_R12M', '이용개월수_할부_R12M', '이용개월수_할부_유이자_R12M', '이용개월수_할부_무이자_R12M', '이용개월수_부분무이자_R12M', '이용개월수_CA_R12M', '이용개월수_체크_R12M', '이용개월수_카드론_R12M', '이용건수_신용_R6M', '이용건수_신판_R6M', '이용건수_일시불_R6M', '이용건수_할부_R6M', '이용건수_할부_유이자_R6M', '이용건수_할부_무이자_R6M', '이용건수_부분무이자_R6M', '이용건수_CA_R6M', '이용건수_체크_R6M', '이용건수_카드론_R6M', '이용금액_일시불_R6M', '이용금액_할부_R6M', '이용금액_할부_유이자_R6M', '이용금액_할부_무이자_R6M', '이용금액_부분무이자_R6M', '이용금액_CA_R6M', '이용금액_체크_R6M', '이용금액_카드론_R6M', '이용개월수_신용_R6M', '이용개월수_신판_R6M', '이용개월수_일시불_R6M', '이용개월수_할부_R6M', '이용개월수_할부_유이자_R6M', '이용개월수_할부_무이자_R6M', '이용개월수_부분무이자_R6M', '이용개월수_CA_R6M', '이용개월수_체크_R6M', '이용개월수_카드론_R6M', '이용건수_신용_R3M', '이용건수_신판_R3M', '이용건수_일시불_R3M', '이용건수_할부_R3M', '이용건수_할부_유이자_R3M', '이용건수_할부_무이자_R3M', '이용건수_부분무이자_R3M', '이용건수_CA_R3M', '이용건수_체크_R3M', '이용건수_카드론_R3M', '이용금액_일시불_R3M', '이용금액_할부_R3M', '이용금액_할부_유이자_R3M', '이용금액_할부_무이자_R3M', '이용금액_부분무이자_R3M', '이용금액_CA_R3M', '이용금액_체크_R3M', '이용금액_카드론_R3M', '이용개월수_신용_R3M', '이용개월수_신판_R3M', '이용개월수_일시불_R3M', '이용개월수_할부_R3M', '이용개월수_할부_유이자_R3M', '이용개월수_할부_무이자_R3M', '이용개월수_부분무이자_R3M', '이용개월수_CA_R3M', '이용개월수_체크_R3M', '이용개월수_카드론_R3M', '이용가맹점수', '이용금액_해외', '쇼핑_도소매_이용금액', '쇼핑_백화점_이용금액', '쇼핑_마트_이용금액', '쇼핑_슈퍼마켓_이용금액', '쇼핑_편의점_이용금액', '쇼핑_아울렛_이용금액', '쇼핑_온라인_이용금액', '쇼핑_기타_이용금액', '교통_주유이용금액', '교통_정비이용금액', '교통_통행료이용금액', '교통_버스지하철이용금액', '교통_택시이용금액', '교통_철도버스이용금액', '여유_운동이용금액', '여유_Pet이용금액', '여유_공연이용금액', '여유_공원이용금액', '여유_숙박이용금액', '여유_여행이용금액', '여유_항공이용금액', '여유_기타이용금액', '납부_통신비이용금액', '납부_관리비이용금액', '납부_렌탈료이용금액', '납부_가스전기료이용금액', '납부_보험료이용금액', '납부_유선방송이용금액', '납부_건강연금이용금액', '납부_기타이용금액', '_1순위업종', '_1순위업종_이용금액', '_2순위업종', '_2순위업종_이용금액', '_3순위업종', '_3순위업종_이용금액', '_1순위쇼핑업종', '_1순위쇼핑업종_이용금액', '_2순위쇼핑업종', '_2순위쇼핑업종_이용금액', '_3순위쇼핑업종', '_3순위쇼핑업종_이용금액', '_1순위교통업종', '_1순위교통업종_이용금액', '_2순위교통업종', '_2순위교통업종_이용금액', '_3순위교통업종', '_3순위교통업종_이용금액', '_1순위여유업종', '_1순위여유업종_이용금액', '_2순위여유업종', '_2순위여유업종_이용금액', '_3순위여유업종', '_3순위여유업종_이용금액', '_1순위납부업종', '_1순위납부업종_이용금액', '_2순위납부업종', '_2순위납부업종_이용금액', '_3순위납부업종', '_3순위납부업종_이용금액', '할부건수_3M_R12M', '할부건수_6M_R12M', '할부건수_12M_R12M', '할부건수_14M_R12M', '할부금액_3M_R12M', '할부금액_6M_R12M', '할부금액_12M_R12M', '할부금액_14M_R12M', '할부건수_유이자_3M_R12M', '할부건수_유이자_6M_R12M', '할부건수_유이자_12M_R12M', '할부건수_유이자_14M_R12M', '할부금액_유이자_3M_R12M', '할부금액_유이자_6M_R12M', '할부금액_유이자_12M_R12M', '할부금액_유이자_14M_R12M', '할부건수_무이자_3M_R12M', '할부건수_무이자_6M_R12M', '할부건수_무이자_12M_R12M', '할부건수_무이자_14M_R12M', '할부금액_무이자_3M_R12M', '할부금액_무이자_6M_R12M', '할부금액_무이자_12M_R12M', '할부금액_무이자_14M_R12M', '할부건수_부분_3M_R12M', '할부건수_부분_6M_R12M', '할부건수_부분_12M_R12M', '할부건수_부분_14M_R12M', '할부금액_부분_3M_R12M', '할부금액_부분_6M_R12M', '할부금액_부분_12M_R12M', '할부금액_부분_14M_R12M', 'RP건수_B0M', 'RP금액_B0M', 'RP유형건수_B0M', 'RP건수_통신_B0M', 'RP건수_아파트_B0M', 'RP건수_제휴사서비스직접판매_B0M', 'RP건수_렌탈_B0M', 'RP건수_가스_B0M', 'RP건수_전기_B0M', 'RP건수_보험_B0M', 'RP건수_학습비_B0M', 'RP건수_유선방송_B0M', 'RP건수_건강_B0M', 'RP건수_교통_B0M', 'RP후경과월', 'RP후경과월_통신', 'RP후경과월_아파트', 'RP후경과월_제휴사서비스직접판매', 'RP후경과월_렌탈', 'RP후경과월_가스', 'RP후경과월_전기', 'RP후경과월_보험', 'RP후경과월_학습비', 'RP후경과월_유선방송', 'RP후경과월_건강', 'RP후경과월_교통', '증감_RP건수_전월', '증감_RP유형건수_전월', '증감_RP건수_통신_전월', '증감_RP건수_아파트_전월', '증감_RP건수_제휴사서비스직접판매_전월', '증감_RP건수_렌탈_전월', '증감_RP건수_가스_전월', '증감_RP건수_전기_전월', '증감_RP건수_보험_전월', '증감_RP건수_학습비_전월', '증감_RP건수_유선방송_전월', '증감_RP건수_건강_전월', '증감_RP건수_교통_전월', '최초카드론이용경과월', '최종카드론이용경과월', '카드론이용건수_누적', '카드론이용월수_누적', '카드론이용금액_누적', '최종카드론_금융상환방식코드', '최종카드론_신청경로코드', '최종카드론_대출이율', '최종카드론_대출일자', '최종카드론_대출월수', '최종카드론_거치개월수', '최종카드론_대출금액', '이용개월수_온라인_R6M', '이용개월수_오프라인_R6M', '이용금액_온라인_R6M', '이용금액_오프라인_R6M', '이용건수_온라인_R6M', '이용건수_오프라인_R6M', '이용금액_온라인_R3M', '이용금액_오프라인_R3M', '이용건수_온라인_R3M', '이용건수_오프라인_R3M', '이용금액_온라인_B0M', '이용금액_오프라인_B0M', '이용건수_온라인_B0M', '이용건수_오프라인_B0M', '이용개월수_페이_온라인_R6M', '이용개월수_페이_오프라인_R6M', '이용금액_페이_온라인_R6M', '이용금액_페이_오프라인_R6M', '이용건수_페이_온라인_R6M', '이용건수_페이_오프라인_R6M', '이용금액_페이_온라인_R3M', '이용금액_페이_오프라인_R3M', '이용건수_페이_온라인_R3M', '이용건수_페이_오프라인_R3M', '이용금액_페이_온라인_B0M', '이용금액_페이_오프라인_B0M', '이용건수_페이_온라인_B0M', '이용건수_페이_오프라인_B0M', '이용개월수_간편결제_R6M', '이용개월수_당사페이_R6M', '이용개월수_당사기타_R6M', '이용개월수_A페이_R6M', '이용개월수_B페이_R6M', '이용개월수_C페이_R6M', '이용개월수_D페이_R6M', '이용금액_간편결제_R6M', '이용금액_당사페이_R6M', '이용금액_당사기타_R6M', '이용금액_A페이_R6M', '이용금액_B페이_R6M', '이용금액_C페이_R6M', '이용금액_D페이_R6M', '이용건수_간편결제_R6M', '이용건수_당사페이_R6M', '이용건수_당사기타_R6M', '이용건수_A페이_R6M', '이용건수_B페이_R6M', '이용건수_C페이_R6M', '이용건수_D페이_R6M', '이용금액_간편결제_R3M', '이용금액_당사페이_R3M', '이용금액_당사기타_R3M', '이용금액_A페이_R3M', '이용금액_B페이_R3M', '이용금액_C페이_R3M', '이용금액_D페이_R3M', '이용건수_간편결제_R3M', '이용건수_당사페이_R3M', '이용건수_당사기타_R3M', '이용건수_A페이_R3M', '이용건수_B페이_R3M', '이용건수_C페이_R3M', '이용건수_D페이_R3M', '이용금액_간편결제_B0M', '이용금액_당사페이_B0M', '이용금액_당사기타_B0M', '이용금액_A페이_B0M', '이용금액_B페이_B0M', '이용금액_C페이_B0M', '이용금액_D페이_B0M', '이용건수_간편결제_B0M', '이용건수_당사페이_B0M', '이용건수_당사기타_B0M', '이용건수_A페이_B0M', '이용건수_B페이_B0M', '이용건수_C페이_B0M', '이용건수_D페이_B0M', '이용개월수_선결제_R6M', '이용횟수_선결제_R6M', '이용금액_선결제_R6M', '이용건수_선결제_R6M', '이용횟수_선결제_R3M', '이용금액_선결제_R3M', '이용건수_선결제_R3M', '이용횟수_선결제_B0M', '이용금액_선결제_B0M', '이용건수_선결제_B0M', '이용횟수_연체_R6M', '이용금액_연체_R6M', '이용횟수_연체_R3M', '이용금액_연체_R3M', '이용횟수_연체_B0M', '이용금액_연체_B0M', '이용개월수_전체_R6M', '이용개월수_전체_R3M', '이용개월수_결제일_R6M', '이용개월수_결제일_R3M', '가맹점매출금액_B1M', '가맹점매출금액_B2M', '정상청구원금_B0M', '선입금원금_B0M', '정상입금원금_B0M', '연체입금원금_B0M', '정상청구원금_B2M', '선입금원금_B2M', '정상입금원금_B2M', '연체입금원금_B2M', '정상청구원금_B5M', '선입금원금_B5M', '정상입금원금_B5M', '연체입금원금_B5M', '건수_할부전환_R6M', '건수_할부전환_R3M', '금액_할부전환_R6M', '금액_할부전환_R3M', '연속무실적개월수_기본_24M_카드', '연속유실적개월수_기본_24M_카드', '신청건수_ATM_CA_B0', '신청건수_ATM_CL_B0', '신청건수_ATM_CA_R6M', '신청건수_ATM_CL_R6M', '승인거절건수_B0M', '승인거절건수_한도초과_B0M', '승인거절건수_BL_B0M', '승인거절건수_입력오류_B0M', '승인거절건수_기타_B0M', '승인거절건수_R3M', '승인거절건수_한도초과_R3M', '승인거절건수_BL_R3M', '승인거절건수_입력오류_R3M', '승인거절건수_기타_R3M', '이용금액대']

In [10]:
ex1 = ex1.fillna(-1)
ex1

,기준년월,ID,최종이용일자_기본,최종이용일자_신판,최종이용일자_CA,최종이용일자_카드론,최종이용일자_체크,최종이용일자_일시불,최종이용일자_할부,이용건수_신용_B0M,...,승인거절건수_BL_B0M,승인거절건수_입력오류_B0M,승인거절건수_기타_B0M,승인거절건수_R3M,승인거절건수_한도초과_R3M,승인거절건수_BL_R3M,승인거절건수_입력오류_R3M,승인거절건수_기타_R3M,이용금액대,Segment
0,201807,TRAIN_000000,20180719,20180713,20180719,10101,20180203,20180709,20180713,11,...,0,0,0,3,3,0,0,0,0,D
1,201807,TRAIN_000001,20180719,20180719,20170728,20170327,10101,20180719,20171231,13,...,0,0,0,3,3,0,0,0,2,E
2,201807,TRAIN_000002,20180706,20180706,20180706,20151119,20141230,20180706,20180627,12,...,0,0,0,0,0,0,0,0,0,C
3,201807,TRAIN_000003,20180721,20180715,20180721,10101,20141111,20180704,20180715,6,...,0,0,0,3,3,0,0,0,0,D
4,201807,TRAIN_000004,20180124,20180124,10101,10101,20180512,20180124,10101,-2,...,0,0,0,0,0,0,0,0,5,E
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2399995,201812,TRAIN_399995,20181220,20181220,10101,10101,20181212,20181220,20160501,2,...,0,0,0,0,0,0,0,0,5,E
2399996,201812,TRAIN_399996,20181202,20181202,10101,20170112,10101,20181202,20180112,10,...,0,0,0,0,0,0,0,0,0,D
2399997,201812,TRAIN_399997,20181230,20181230,10101,10101,20131124,20181230,20180919,10,...,0,0,0,0,0,0,0,0,1,C
2399998,201812,TRAIN_399998,20161224,20161224,10101,10101,10101,20161224,20150122,-2,...,0,0,0,0,0,0,0,0,5,E
2399999,201812,TRAIN_399999,20180831,20180831,10101,10101,10101,20180831,20180713,-1,...,0,0,0,0,0,0,0,0,3,E

In [11]:
missing_mask = ex1.isna() | (ex1 == -1)
missing_ratio = missing_mask.mean()

high_na = missing_ratio[missing_ratio > 0.2].index.tolist()

high_const_cols = []
threshold_const = 0.8

for col in ex1.columns:
    top_ratio = ex1[col].value_counts(normalize=True, dropna=False).values[0]
    if top_ratio > threshold_const:
        high_const_cols.append(col)

to_drop = list(set(high_na + high_const_cols))

if 'Segment' in to_drop:
    to_drop.remove('Segment')

print("삭제 대상 컬럼 (결측>20% 또는 동일값>80%):", to_drop)

ex1.drop(columns=to_drop, inplace=True)

삭제 대상 컬럼 (결측>20% 또는 동일값>80%): ['최대이용금액_부분무이자_R12M', '할부건수_무이자_6M_R12M', '최종카드론_신청경로코드', '최대이용금액_카드론_R12M', '이용금액_CA_R3M', '이용건수_B페이_B0M', '이용건수_A페이_R6M', '증감_RP건수_렌탈_전월', '이용건수_부분무이자_B0M', '이용금액_할부_무이자_B0M', '이용금액_A페이_B0M', 'RP후경과월_학습비', '여유_여행이용금액', '증감_RP건수_아파트_전월', '할부금액_유이자_12M_R12M', '이용개월수_카드론_R6M', '이용금액_부분무이자_R12M', '이용금액_C페이_R6M', '건수_할부전환_R3M', '승인거절건수_BL_B0M', '이용건수_할부_B0M', 'RP후경과월_가스', '이용금액_연체_R6M', '최종이용일자_카드론', '이용건수_부분무이자_R6M', '이용금액_CA_R6M', '이용건수_당사페이_R3M', '이용개월수_할부_유이자_R6M', '할부건수_유이자_14M_R12M', '할부금액_14M_R12M', '이용금액_당사기타_B0M', '금액_할부전환_R6M', '쇼핑_백화점_이용금액', '할부금액_유이자_6M_R12M', '이용금액_부분무이자_B0M', '이용금액_CA_R12M', '최대이용금액_CA_R12M', '이용금액_해외', '이용금액_할부_유이자_B0M', '교통_철도버스이용금액', 'RP건수_렌탈_B0M', '이용금액_선결제_R6M', '신청건수_ATM_CL_B0', '_3순위여유업종', '이용건수_할부_유이자_R12M', '여유_숙박이용금액', '이용금액_C페이_B0M', '여유_항공이용금액', '이용건수_D페이_B0M', '최종카드론_거치개월수', '이용건수_CA_R3M', '증감_RP건수_교통_전월', '증감_RP건수_유선방송_전월', '이용후경과월_카드론', '할부금액_부분_12M_R12M', '이용후경과월_CA', '이용금액_할부_무이자_R3M', '할부금액_부분_14M_R12M', 'RP후경과월_제휴사서비스직접판매', '이용건수_선결제_B0M', '할부건수_부분_12M_R12M', '이용금액_페이_오프라인_B0M', '이용건수_카드론_R3M', '이용개월수_할부_유이자_R3M', '이용건수_체크_R3M', '증감_RP건수_보험_전월', '이용금액_연체_R3M', '이용금액_체크_R6M', '승인거절건수_R3M', 'RP건수_건강_B0M', '이용건수_페이_오프라인_R6M', '할부건수_유이자_3M_R12M', '증감_RP유형건수_전월', '증감_RP건수_가스_전월', '이용건수_온라인_B0M', '_2순위여유업종', '이용건수_할부_유이자_R6M', '이용건수_C페이_R3M', '이용금액_A페이_R3M', '이용금액_당사페이_R6M', '최종카드론_대출금액', '선입금원금_B5M', '이용금액_D페이_R3M', '증감_RP건수_제휴사서비스직접판매_전월', '이용건수_카드론_B0M', '이용건수_선결제_R6M', '할부금액_무이자_12M_R12M', '이용건수_CA_R12M', '최종카드론이용경과월', '납부_보험료이용금액', '이용건수_페이_오프라인_R3M', '이용금액_할부_유이자_R3M', '이용개월수_부분무이자_R6M', 'RP후경과월_건강', '이용금액_할부_B0M', '이용건수_B페이_R3M', '이용개월수_할부_무이자_R3M', '할부건수_6M_R12M', '교통_통행료이용금액', '이용개월수_B페이_R6M', '승인거절건수_입력오류_R3M', '이용금액_체크_B0M', '최종카드론_대출일자', '이용금액_D페이_R6M', '이용건수_부분무이자_R3M', '_3순위납부업종_이용금액', '이용개월수_부분무이자_R12M', '이용건수_D페이_R6M', '이용금액_페이_오프라인_R3M', '이용금액_체크_R3M', '이용건수_할부_무이자_R3M', '할부금액_유이자_3M_R12M', 'RP건수_전기_B0M', 'RP후경과월_보험', 'RP건수_학습비_B0M', '여유_공연이용금액', '납부_건강연금이용금액', '할부건수_무이자_14M_R12M', '이용개월수_A페이_R6M', '이용금액_C페이_R3M', '이용건수_A페이_B0M', '증감_RP건수_전기_전월', '승인거절건수_한도초과_R3M', '이용건수_할부_유이자_R3M', '_2순위납부업종', '신청건수_ATM_CA_B0', '이용건수_할부_유이자_B0M', '승인거절건수_한도초과_B0M', '이용횟수_연체_R3M', '가맹점매출금액_B2M', '이용건수_CA_R6M', '할부금액_부분_6M_R12M', '이용건수_페이_오프라인_B0M', '이용개월수_카드론_R12M', '이용건수_카드론_R6M', '이용횟수_선결제_R3M', '할부건수_유이자_12M_R12M', '이용건수_선결제_R3M', '이용금액_카드론_R12M', 'RP후경과월_렌탈', '승인거절건수_B0M', '최초카드론이용경과월', '이용금액_CA_B0M', '할부금액_12M_R12M', '건수_할부전환_R6M', 'RP건수_보험_B0M', '이용개월수_카드론_R3M', '가맹점매출금액_B1M', '여유_Pet이용금액', '선입금원금_B2M', '최종카드론_대출월수', '할부건수_부분_14M_R12M', 'RP후경과월_아파트', '이용금액_카드론_R6M', 'RP후경과월_전기', '금액_할부전환_R3M', '납부_렌탈료이용금액', '이용건수_체크_R6M', '쇼핑_아울렛_이용금액', '증감_RP건수_학습비_전월', '여유_공원이용금액', '이용금액_B페이_B0M', '이용건수_당사기타_B0M', '이용금액_선결제_B0M', '카드론이용월수_누적', '할부건수_부분_6M_R12M', '승인거절건수_입력오류_B0M', 'RP건수_유선방송_B0M', '이용금액_A페이_R6M', '선입금원금_B0M', '이용개월수_선결제_R6M', '이용후경과월_부분무이자', '이용횟수_선결제_B0M', '이용건수_C페이_B0M', '이용개월수_CA_R12M', '이용금액_선결제_R3M', '이용횟수_선결제_R6M', '카드론이용건수_누적', '이용건수_당사페이_B0M', '이용건수_부분무이자_R12M', '이용개월수_CA_R3M', '이용금액_페이_오프라인_R6M', '이용금액_당사기타_R6M', '이용건수_당사페이_R6M', '할부금액_무이자_14M_R12M', '증감_RP건수_건강_전월', '신청건수_ATM_CA_R6M', '이용금액_당사기타_R3M', '_3순위교통업종_이용금액', '이용개월수_당사기타_R6M', '이용개월수_부분무이자_R3M', '이용건수_CA_B0M', '증감_RP건수_통신_전월', '이용금액_카드론_B0M', '이용건수_체크_B0M', '이용개월수_D페이_R6M', '이용건수_A페이_R3M', '이용건수_당사기타_R6M', '신청건수_ATM_CL_R6M', '승인거절건수_기타_B0M', '이용후경과월_체크', '여유_운동이용금액', '이용건수_C페이_R6M', '할부금액_부분_3M_R12M', '최종카드론_금융상환방식코드', '할부건수_12M_R12M', 'RP건수_아파트_B0M', '이용개월수_당사페이_R6M', '이용금액_B페이_R3M', '_2순위납부업종_이용금액', '이용개월수_C페이_R6M', '이용금액_당사페이_B0M', '납부_관리비이용금액', '이용금액_당사페이_R3M', '_2순위여유업종_이용금액', '카드론이용금액_누적', '이용횟수_연체_R6M', '_1순위여유업종', '납부_유선방송이용금액', '_1순위여유업종_이용금액', '할부금액_유이자_14M_R12M', '증감_RP건수_전월', '이용금액_B페이_R6M', '이용건수_D페이_R3M', '여유_기타이용금액', '이용건수_B페이_R6M', '승인거절건수_BL_R3M', '이용건수_카드론_R12M', '최종카드론_대출이율', 'RP건수_가스_B0M', '이용개월수_체크_R6M', '할부건수_무이자_12M_R12M', '이용금액_할부_유이자_R6M', '이용개월수_CA_R6M', '이용금액_D페이_B0M', '이용금액_연체_B0M', '할부건수_부분_3M_R12M', 'RP후경과월_유선방송', '이용개월수_페이_오프라인_R6M', '_3순위교통업종', '_3순위납부업종', '이용건수_할부_R3M', '할부건수_유이자_6M_R12M', '이용횟수_연체_B0M', '이용건수_할부_무이자_B0M', '이용개월수_체크_R3M', '_3순위여유업종_이용금액', '할부건수_14M_R12M', 'RP건수_제휴사서비스직접판매_B0M', '이용건수_당사기타_R3M', '승인거절건수_기타_R3M', '이용금액_카드론_R3M', '납부_가스전기료이용금액']

In [12]:
num_df = ex1.select_dtypes(include=[np.number]).dropna()
low_var = num_df.var()[ num_df.var() < 0.01 ].index.tolist()
low_var

[]

In [13]:
import pandas as pd
import numpy as np

num_df = ex1.select_dtypes(include=[np.number]).dropna()

corr = num_df.corr().abs()

high_corr_pairs = (
    corr.where(np.triu(np.ones(corr.shape), k=1).astype(bool))
        .stack()
        .reset_index()
)
high_corr_pairs.columns = ['Feature_1', 'Feature_2', 'Correlation']
high_corr_pairs = high_corr_pairs[high_corr_pairs['Correlation'] > 0.8]

if not np.issubdtype(ex1['Segment'].dtype, np.number):
    segment_map = {label: idx for idx, label in enumerate(sorted(ex1['Segment'].unique()))}
    ex1['Segment_encoded'] = ex1['Segment'].map(segment_map)
else:
    ex1['Segment_encoded'] = ex1['Segment']

segment_corr = ex1[num_df.columns].corrwith(ex1['Segment_encoded']).abs()

high_corr_pairs['Corr_with_Segment_1'] = high_corr_pairs['Feature_1'].map(segment_corr)
high_corr_pairs['Corr_with_Segment_2'] = high_corr_pairs['Feature_2'].map(segment_corr)


high_corr_pairs = high_corr_pairs.sort_values(by='Correlation', ascending=False).reset_index(drop=True)

print(f"▶ 상관계수 초과 변수쌍 수: {len(high_corr_pairs)}")
display(high_corr_pairs)

▶ 상관계수 초과 변수쌍 수: 593

,Feature_1,Feature_2,Correlation,Corr_with_Segment_1,Corr_with_Segment_2
0,이용건수_신용_R12M,이용건수_신판_R12M,0.999881,0.480732,0.476833
1,이용건수_신용_R6M,이용건수_신판_R6M,0.999862,0.436528,0.432737
2,이용건수_신용_R3M,이용건수_신판_R3M,0.999836,0.433638,0.429748
3,이용건수_신용_B0M,이용건수_신판_B0M,0.999802,0.436677,0.432548
4,이용건수_신판_R3M,이용건수_일시불_R3M,0.999771,0.429748,0.426715
...,...,...,...,...,...
588,정상청구원금_B0M,정상입금원금_B2M,0.800296,0.634571,0.536208
589,이용금액_일시불_R12M,정상청구원금_B5M,0.800286,0.595858,0.660738
590,이용금액_일시불_B0M,정상입금원금_B0M,0.800075,0.575032,0.549280
591,이용금액_일시불_B0M,이용건수_일시불_R12M,0.800072,0.575032,0.472362
592,이용금액_일시불_B0M,이용건수_신판_R12M,0.800053,0.575032,0.476833

In [14]:
to_drop = []

for _, row in high_corr_pairs.iterrows():
    f1, f2 = row['Feature_1'], row['Feature_2']
    c1, c2 = row['Corr_with_Segment_1'], row['Corr_with_Segment_2']
    
    # 결측값 건너뛰기
    if pd.isna(c1) or pd.isna(c2):
        continue

    # 둘 중 하나라도 Segment와의 상관계수가 0.3 이상이면 건너뜀
    if abs(c1) >= 0.3 or abs(c2) >= 0.3:
        continue

    # 둘 다 0.3 미만일 때: Segment와 더 상관관계가 낮은 쪽 제거
    if abs(c1) < abs(c2):
        to_drop.append(f1)
    else:
        to_drop.append(f2)

# 중복 제거
to_drop = list(set(to_drop))

# 결과 출력
print(f"▶ 제거 대상 피처 수: {len(to_drop)}")
print("제거할 피처 목록:")
print(to_drop)

▶ 제거 대상 피처 수: 45
제거할 피처 목록:
['RP건수_통신_B0M', '이용개월수_일시불_R6M', '최종이용일자_신판', '이용후경과월_할부', '이용건수_할부_무이자_R6M', '이용건수_할부_무이자_R12M', '이용개월수_일시불_R12M', '이용후경과월_신용', '이용개월수_전체_R3M', '이용개월수_신용_R3M', '이용금액_할부_R6M', '이용건수_체크_R12M', '이용개월수_신용_R6M', '납부_통신비이용금액', '교통_버스지하철이용금액', '연속무실적개월수_기본_24M_카드', '이용건수_할부_R6M', '이용금액_할부_R3M', '이용개월수_신판_R6M', '최대이용금액_체크_R12M', '이용개월수_일시불_R3M', '최종이용일자_기본', '이용건수_할부_R12M', '이용개월수_할부_R12M', '이용개월수_전체_R6M', '이용후경과월_신판', '이용금액_할부_유이자_R12M', '이용개월수_신판_R12M', '이용개월수_할부_무이자_R6M', 'RP유형건수_B0M', '할부금액_무이자_6M_R12M', '이용개월수_결제일_R6M', '이용후경과월_할부_무이자', '이용개월수_신판_R3M', 'RP후경과월_통신', '할부건수_3M_R12M', '이용개월수_할부_R6M', 'RP건수_교통_B0M', '이용개월수_할부_R3M', '이용후경과월_할부_유이자', '이용개월수_체크_R12M', '이용개월수_할부_유이자_R12M', '이용개월수_결제일_R3M', '할부건수_무이자_3M_R12M', '이용개월수_오프라인_R6M']

In [15]:
cols_to_drop = ['RP건수_통신_B0M', '이용개월수_일시불_R6M', '최종이용일자_신판', '이용후경과월_할부', '이용건수_할부_무이자_R6M', '이용건수_할부_무이자_R12M', '이용개월수_일시불_R12M', '이용후경과월_신용', '이용개월수_전체_R3M', '이용개월수_신용_R3M', '이용금액_할부_R6M', '이용건수_체크_R12M', '이용개월수_신용_R6M', '납부_통신비이용금액', '교통_버스지하철이용금액', '연속무실적개월수_기본_24M_카드', '이용건수_할부_R6M', '이용금액_할부_R3M', '이용개월수_신판_R6M', '최대이용금액_체크_R12M', '이용개월수_일시불_R3M', '최종이용일자_기본', '이용건수_할부_R12M', '이용개월수_할부_R12M', '이용개월수_전체_R6M', '이용후경과월_신판', '이용금액_할부_유이자_R12M', '이용개월수_신판_R12M', '이용개월수_할부_무이자_R6M', 'RP유형건수_B0M', '할부금액_무이자_6M_R12M', '이용개월수_결제일_R6M', '이용후경과월_할부_무이자', '이용개월수_신판_R3M', 'RP후경과월_통신', '할부건수_3M_R12M', '이용개월수_할부_R6M', 'RP건수_교통_B0M', '이용개월수_할부_R3M', '이용후경과월_할부_유이자', '이용개월수_체크_R12M', '이용개월수_할부_유이자_R12M', '이용개월수_결제일_R3M', '할부건수_무이자_3M_R12M', '이용개월수_오프라인_R6M']
ex1.drop(columns=cols_to_drop, inplace=True)

In [17]:
from statsmodels.tools.tools import add_constant
from statsmodels.stats.outliers_influence import variance_inflation_factor

num_df = (
    ex1
    .select_dtypes(include=[np.number])
    .drop(columns=['기준년월'], errors='ignore')
    .dropna()
)


X = add_constant(num_df)

vif_df = pd.DataFrame({
    'feature': X.columns,
    'VIF': [variance_inflation_factor(X.values, i)
            for i in range(X.shape[1])]
})

vif_df = vif_df[vif_df['feature'] != 'const'].reset_index(drop=True)

high_vif = vif_df[vif_df['VIF'] > 10]

print("VIF > 10인 컬럼들:", high_vif['feature'].tolist())
print(high_vif)

VIF > 10인 컬럼들: []
Empty DataFrame
Columns: [feature, VIF]
Index: []

In [19]:
from sklearn.preprocessing import LabelEncoder

df_corr = ex1.drop(columns=['기준년월', 'ID']).copy()

le = LabelEncoder()
df_corr['Segment_encoded'] = le.fit_transform(df_corr['Segment'])

correlations = df_corr.corr(numeric_only=True)['Segment_encoded'].drop('Segment_encoded')

selected_cols = correlations[correlations.abs() > 0.2].index.tolist()

final_cols = ['기준년월', 'ID','Segment'] + selected_cols

ex1_filtered = ex1[final_cols]

In [20]:
cols = ex1_filtered.columns.tolist()
cols

['기준년월',
 'ID',
 'Segment',
 '최종이용일자_CA',
 '최종이용일자_할부',
 '이용건수_신용_B0M',
 '이용건수_신판_B0M',
 '이용건수_일시불_B0M',
 '이용금액_일시불_B0M',
 '이용건수_신용_R12M',
 '이용건수_신판_R12M',
 '이용건수_일시불_R12M',
 '이용금액_일시불_R12M',
 '이용금액_할부_R12M',
 '이용금액_할부_무이자_R12M',
 '이용금액_체크_R12M',
 '최대이용금액_일시불_R12M',
 '최대이용금액_할부_R12M',
 '최대이용금액_할부_무이자_R12M',
 '이용개월수_신용_R12M',
 '이용개월수_할부_무이자_R12M',
 '이용건수_신용_R6M',
 '이용건수_신판_R6M',
 '이용건수_일시불_R6M',
 '이용금액_일시불_R6M',
 '이용금액_할부_무이자_R6M',
 '이용건수_신용_R3M',
 '이용건수_신판_R3M',
 '이용건수_일시불_R3M',
 '이용금액_일시불_R3M',
 '이용가맹점수',
 '쇼핑_도소매_이용금액',
 '쇼핑_마트_이용금액',
 '쇼핑_슈퍼마켓_이용금액',
 '쇼핑_편의점_이용금액',
 '쇼핑_온라인_이용금액',
 '쇼핑_기타_이용금액',
 '교통_주유이용금액',
 '교통_정비이용금액',
 '교통_택시이용금액',
 '납부_기타이용금액',
 '_1순위업종',
 '_1순위업종_이용금액',
 '_2순위업종_이용금액',
 '_3순위업종',
 '_3순위업종_이용금액',
 '_1순위쇼핑업종',
 '_1순위쇼핑업종_이용금액',
 '_2순위쇼핑업종_이용금액',
 '_3순위쇼핑업종_이용금액',
 '_1순위교통업종',
 '_1순위교통업종_이용금액',
 '_2순위교통업종',
 '_2순위교통업종_이용금액',
 '_1순위납부업종_이용금액',
 '할부금액_3M_R12M',
 '할부금액_6M_R12M',
 '할부금액_무이자_3M_R12M',
 'RP건수_B0M',
 '이용개월수_온라인_R6M',
 '이용금액_온라인_R6M',
 '이용금액_오프라인_R6M',
 '이용건수_온라인_R6M',
 '이용건수_오프라인_R6M',
 '이용금액_온라인_R3M',
 '이용금액_오프라인_R3M',
 '이용건수_온라인_R3M',
 '이용건수_오프라인_R3M',
 '이용금액_온라인_B0M',
 '이용금액_오프라인_B0M',
 '이용건수_오프라인_B0M',
 '이용개월수_페이_온라인_R6M',
 '이용금액_페이_온라인_R6M',
 '이용건수_페이_온라인_R6M',
 '이용금액_페이_온라인_R3M',
 '이용건수_페이_온라인_R3M',
 '이용금액_페이_온라인_B0M',
 '이용건수_페이_온라인_B0M',
 '이용개월수_간편결제_R6M',
 '이용금액_간편결제_R6M',
 '이용건수_간편결제_R6M',
 '이용금액_간편결제_R3M',
 '이용건수_간편결제_R3M',
 '이용금액_간편결제_B0M',
 '이용건수_간편결제_B0M',
 '정상청구원금_B0M',
 '정상입금원금_B0M',
 '연체입금원금_B0M',
 '정상청구원금_B2M',
 '정상입금원금_B2M',
 '연체입금원금_B2M',
 '정상청구원금_B5M',
 '정상입금원금_B5M',
 '연체입금원금_B5M',
 '연속유실적개월수_기본_24M_카드',
 '이용금액대']

In [21]:
ex1_filtered.to_parquet('승인_전처리_Segment.parquet', index=False)